// This file is auto-generated by scripts/generateConstants

export const battleCodes = [
  "BigSlope", // 과메기 온천
  "Carousel", // 초밥 월드
  "Cross", // 수랑정
  "District", // 메기 지구
  "Factory", // 남플라 유적
  "Hiagari", // 만새기 리조트＆스파
  "Jyoheki", // 넙치 언덕 단지
  "Kaisou", // 고등어 해협 대교
  "Line", // 혹등 마켓
  "Nagasaki", // 철갑상어 조선소
  "Pillar", // 만타 마리아호
  "Pivot", // 도미 미술관
  "Propeller", // 청새치 공항
  "Ruins", // 참치 탄광
  "Scrap", // 나메로우 금속
  "Section", // 대구 포트 쇼핑 파크
  "Spider", // 거미게 경제특구
  "Temple", // 맛조개 방수로
  "Twist", // 광어 해운
  "Upland", // 해녀 미술 대학
  "Wave", // 다시마 트랙
  "Yagara", // 대치 시장
  "Yunohana", // 석순 대협곡
] as const;

export const battleCodeToData = {
  "BigSlope": {
    "code": "BigSlope",
    "labels": {
      "KRko": "과메기 온천",
      "JPja": "クサヤ温泉",
      "USen": "Brinewater Springs",
    },
  },
  "Carousel": {
    "code": "Carousel",
    "labels": {
      "KRko": "초밥 월드",
      "JPja": "スメーシーワールド",
      "USen": "Wahoo World",
    },
  },
  "Cross": {
    "code": "Cross",
    "labels": { "KRko": "수랑정", "JPja": "バイガイ亭", "USen": "Robo ROM-en" },
  },
  "District": {
    "code": "District",
    "labels": {
      "KRko": "메기 지구",
      "JPja": "ゴンズイ地区",
      "USen": "Eeltail Alley",
    },
  },
  "Factory": {
    "code": "Factory",
    "labels": {
      "KRko": "남플라 유적",
      "JPja": "ナンプラー遺跡",
      "USen": "Um'ami Ruins",
    },
  },
  "Hiagari": {
    "code": "Hiagari",
    "labels": {
      "KRko": "만새기 리조트＆스파",
      "JPja": "マヒマヒリゾート＆スパ",
      "USen": "Mahi-Mahi Resort",
    },
  },
  "Jyoheki": {
    "code": "Jyoheki",
    "labels": {
      "KRko": "넙치 언덕 단지",
      "JPja": "ヒラメが丘団地",
      "USen": "Flounder Heights",
    },
  },
  "Kaisou": {
    "code": "Kaisou",
    "labels": {
      "KRko": "고등어 해협 대교",
      "JPja": "マサバ海峡大橋",
      "USen": "Hammerhead Bridge",
    },
  },
  "Line": {
    "code": "Line",
    "labels": {
      "KRko": "혹등 마켓",
      "JPja": "ザトウマーケット",
      "USen": "MakoMart",
    },
  },
  "Nagasaki": {
    "code": "Nagasaki",
    "labels": {
      "KRko": "철갑상어 조선소",
      "JPja": "チョウザメ造船",
      "USen": "Sturgeon Shipyard",
    },
  },
  "Pillar": {
    "code": "Pillar",
    "labels": {
      "KRko": "만타 마리아호",
      "JPja": "マンタマリア号",
      "USen": "Manta Maria",
    },
  },
  "Pivot": {
    "code": "Pivot",
    "labels": {
      "KRko": "도미 미술관",
      "JPja": "キンメダイ美術館",
      "USen": "Museum d'Alfonsino",
    },
  },
  "Propeller": {
    "code": "Propeller",
    "labels": {
      "KRko": "청새치 공항",
      "JPja": "カジキ空港",
      "USen": "Marlin Airport",
    },
  },
  "Ruins": {
    "code": "Ruins",
    "labels": {
      "KRko": "참치 탄광",
      "JPja": "ネギトロ炭鉱",
      "USen": "Bluefin Depot",
    },
  },
  "Scrap": {
    "code": "Scrap",
    "labels": {
      "KRko": "나메로우 금속",
      "JPja": "ナメロウ金属",
      "USen": "Mincemeat Metalworks",
    },
  },
  "Section": {
    "code": "Section",
    "labels": {
      "KRko": "대구 포트 쇼핑 파크",
      "JPja": "タラポートショッピングパーク",
      "USen": "Barnacle & Dime",
    },
  },
  "Spider": {
    "code": "Spider",
    "labels": {
      "KRko": "거미게 경제특구",
      "JPja": "タカアシ経済特区",
      "USen": "Crableg Capital",
    },
  },
  "Temple": {
    "code": "Temple",
    "labels": {
      "KRko": "맛조개 방수로",
      "JPja": "マテガイ放水路",
      "USen": "Undertow Spillway",
    },
  },
  "Twist": {
    "code": "Twist",
    "labels": {
      "KRko": "광어 해운",
      "JPja": "オヒョウ海運",
      "USen": "Shipshape Cargo Co.",
    },
  },
  "Upland": {
    "code": "Upland",
    "labels": {
      "KRko": "해녀 미술 대학",
      "JPja": "海女美術大学",
      "USen": "Inkblot Art Academy",
    },
  },
  "Wave": {
    "code": "Wave",
    "labels": {
      "KRko": "다시마 트랙",
      "JPja": "コンブトラック",
      "USen": "Humpback Pump Track",
    },
  },
  "Yagara": {
    "code": "Yagara",
    "labels": {
      "KRko": "대치 시장",
      "JPja": "ヤガラ市場",
      "USen": "Hagglefish Market",
    },
  },
  "Yunohana": {
    "code": "Yunohana",
    "labels": {
      "KRko": "석순 대협곡",
      "JPja": "ユノハナ大渓谷",
      "USen": "Scorch Gorge",
    },
  },
} as const;
