// This file is auto-generated by scripts/generateConstants

export const salmonrunCodes = [
  "Shakedent", // 뫼니 엘 해양 발전소
  "Shakehighway", // 연어알젓 교차로 옛터
  "Shakelift", // 사계절 훈제 공방
  "Shakeship", // 난파선 돈 브라코
  "Shakespiral", // 연어말이 요새
  "Shakeup", // 셰케나 댐
] as const;

export const salmonrunCodeToData = {
  "Shakedent": {
    "code": "Shakedent",
    "labels": {
      "KRko": "뫼니 엘 해양 발전소",
      "JPja": "ムニ・エール海洋発電所",
      "USen": "Gone Fission Hydroplant",
    },
  },
  "Shakehighway": {
    "code": "Shakehighway",
    "labels": {
      "KRko": "연어알젓 교차로 옛터",
      "JPja": "すじこジャンクション跡",
      "USen": "Jammin' Salmon Junction",
    },
  },
  "Shakelift": {
    "code": "Shakelift",
    "labels": {
      "KRko": "사계절 훈제 공방",
      "JPja": "トキシラズいぶし工房",
      "USen": "Salmonid Smokeyard",
    },
  },
  "Shakeship": {
    "code": "Shakeship",
    "labels": {
      "KRko": "난파선 돈 브라코",
      "JPja": "難破船ドン・ブラコ",
      "USen": "Marooner's Bay",
    },
  },
  "Shakespiral": {
    "code": "Shakespiral",
    "labels": {
      "KRko": "연어말이 요새",
      "JPja": "アラマキ砦",
      "USen": "Sockeye Station",
    },
  },
  "Shakeup": {
    "code": "Shakeup",
    "labels": {
      "KRko": "셰케나 댐",
      "JPja": "シェケナダム",
      "USen": "Spawning Grounds",
    },
  },
} as const;
