// This file is auto-generated by scripts/generateWeaponConstants.ts

export const codes = [
  "Blaster_LightLong_00", // Rブラスターエリート
  "Blaster_LightLong_01", // Rブラスターエリートデコ
  "Blaster_LightShort_00", // クラッシュブラスター
  "Blaster_LightShort_01", // クラッシュブラスターネオ
  "Blaster_Light_00", // ラピッドブラスター
  "Blaster_Light_01", // ラピッドブラスターデコ
  "Blaster_Long_00", // ロングブラスター
  "Blaster_Middle_00", // ホットブラスター
  "Blaster_Middle_01", // ホットブラスターカスタム
  "Blaster_Precision_00", // S-BLAST92
  "Blaster_Precision_01", // S-BLAST91
  "Blaster_Short_00", // ノヴァブラスター
  "Blaster_Short_01", // ノヴァブラスターネオ
  "Brush_Heavy_00", // フィンセント
  "Brush_Heavy_01", // フィンセント・ヒュー
  "Brush_Mini_00", // パブロ
  "Brush_Mini_01", // パブロ・ヒュー
  "Brush_Normal_00", // ホクサイ
  "Brush_Normal_01", // ホクサイ・ヒュー
  "Charger_Keeper_00", // ソイチューバー
  "Charger_Keeper_01", // ソイチューバーカスタム
  "Charger_Light_00", // 14式竹筒銃・甲
  "Charger_LongScope_00", // 4Kスコープ
  "Charger_Long_00", // リッター4K
  "Charger_NormalScope_00", // スプラスコープ
  "Charger_NormalScope_01", // スプラスコープコラボ
  "Charger_Normal_00", // スプラチャージャー
  "Charger_Normal_01", // スプラチャージャーコラボ
  "Charger_Pencil_00", // R-PEN/5H
  "Charger_Pencil_01", // R-PEN/5B
  "Charger_Quick_00", // スクイックリンα
  "Maneuver_Dual_00", // デュアルスイーパー
  "Maneuver_Dual_01", // デュアルスイーパーカスタム
  "Maneuver_Gallon_00", // ケルビン525
  "Maneuver_Normal_00", // スプラマニューバー
  "Maneuver_Normal_01", // スプラマニューバーコラボ
  "Maneuver_Short_00", // スパッタリー
  "Maneuver_Short_01", // スパッタリー・ヒュー
  "Maneuver_Stepper_00", // クアッドホッパーブラック
  "Maneuver_Stepper_01", // クアッドホッパーホワイト
  "Roller_Compact_00", // カーボンローラー
  "Roller_Compact_01", // カーボンローラーデコ
  "Roller_Heavy_00", // ダイナモローラー
  "Roller_Heavy_01", // ダイナモローラーテスラ
  "Roller_Hunter_00", // ヴァリアブルローラー
  "Roller_Normal_00", // スプラローラー
  "Roller_Normal_01", // スプラローラーコラボ
  "Roller_Wide_00", // ワイドローラー
  "Roller_Wide_01", // ワイドローラーコラボ
  "Saber_Lite_00", // ドライブワイパー
  "Saber_Lite_01", // ドライブワイパーデコ
  "Saber_Normal_00", // ジムワイパー
  "Saber_Normal_01", // ジムワイパー・ヒュー
  "Shelter_Compact_00", // スパイガジェット
  "Shelter_Compact_01", // スパイガジェットソレーラ
  "Shelter_Normal_00", // パラシェルター
  "Shelter_Normal_01", // パラシェルターソレーラ
  "Shelter_Wide_00", // キャンピングシェルター
  "Shelter_Wide_01", // キャンピングシェルターソレーラ
  "Shooter_Blaze_00", // プロモデラーMG
  "Shooter_Blaze_01", // プロモデラーRG
  "Shooter_Expert_00", // プライムシューター
  "Shooter_Expert_01", // プライムシューターコラボ
  "Shooter_First_00", // わかばシューター
  "Shooter_First_01", // もみじシューター
  "Shooter_Flash_00", // ボトルガイザー
  "Shooter_Flash_01", // ボトルガイザーフォイル
  "Shooter_Gravity_00", // .52ガロン
  "Shooter_Heavy_00", // .96ガロン
  "Shooter_Heavy_01", // .96ガロンデコ
  "Shooter_Long_00", // ジェットスイーパー
  "Shooter_Long_01", // ジェットスイーパーカスタム
  "Shooter_Normal_00", // スプラシューター
  "Shooter_Normal_01", // スプラシューターコラボ
  "Shooter_Normal_H", // ヒーローシューター レプリカ
  "Shooter_Precision_00", // シャープマーカー
  "Shooter_Precision_01", // シャープマーカーネオ
  "Shooter_QuickLong_00", // スペースシューター
  "Shooter_QuickLong_01", // スペースシューターコラボ
  "Shooter_QuickMiddle_00", // N-ZAP85
  "Shooter_QuickMiddle_01", // N-ZAP89
  "Shooter_Short_00", // ボールドマーカー
  "Shooter_Short_01", // ボールドマーカーネオ
  "Shooter_TripleMiddle_00", // H3リールガン
  "Shooter_TripleMiddle_01", // H3リールガンD
  "Shooter_TripleQuick_00", // L3リールガン
  "Shooter_TripleQuick_01", // L3リールガンD
  "Slosher_Bathtub_00", // オーバーフロッシャー
  "Slosher_Bathtub_01", // オーバーフロッシャーデコ
  "Slosher_Diffusion_00", // ヒッセン
  "Slosher_Diffusion_01", // ヒッセン・ヒュー
  "Slosher_Double_00", // モップリン
  "Slosher_Launcher_00", // スクリュースロッシャー
  "Slosher_Launcher_01", // スクリュースロッシャーネオ
  "Slosher_Strong_00", // バケットスロッシャー
  "Slosher_Strong_01", // バケットスロッシャーデコ
  "Slosher_Washtub_00", // エクスプロッシャー
  "Spinner_Downpour_00", // クーゲルシュライバー
  "Spinner_Downpour_01", // クーゲルシュライバー・ヒュー
  "Spinner_HyperShort_00", // イグザミナー
  "Spinner_Hyper_00", // ハイドラント
  "Spinner_Quick_00", // スプラスピナー
  "Spinner_Quick_01", // スプラスピナーコラボ
  "Spinner_Serein_00", // ノーチラス47
  "Spinner_Standard_00", // バレルスピナー
  "Spinner_Standard_01", // バレルスピナーデコ
  "Stringer_Normal_00", // トライストリンガー
  "Stringer_Normal_01", // トライストリンガーコラボ
  "Stringer_Short_00", // LACT-450
  "Stringer_Short_01", // LACT-450デコ
] as const;

export const codeToInfo = {
  "Blaster_LightLong_00": {
    code: "Blaster_LightLong_00",
    label: "Rブラスターエリート",
    innerId: 250,
    subWeapon: "PoisonMist",
    specialWeapon: "SpBlower",
    remoteImgIdent: "Path_Wst_Blaster_LightLong_00.png",
  },
  "Blaster_LightLong_01": {
    code: "Blaster_LightLong_01",
    label: "Rブラスターエリートデコ",
    innerId: 251,
    subWeapon: "LineMarker",
    specialWeapon: "SpMicroLaser",
    remoteImgIdent: "Path_Wst_Blaster_LightLong_01.png",
  },
  "Blaster_LightShort_00": {
    code: "Blaster_LightShort_00",
    label: "クラッシュブラスター",
    innerId: 230,
    subWeapon: "Bomb_Splash",
    specialWeapon: "SpUltraShot",
    remoteImgIdent: "Path_Wst_Blaster_LightShort_00.png",
  },
  "Blaster_LightShort_01": {
    code: "Blaster_LightShort_01",
    label: "クラッシュブラスターネオ",
    innerId: 231,
    subWeapon: "Bomb_Curling",
    specialWeapon: "SpFirework",
    remoteImgIdent: "Path_Wst_Blaster_LightShort_01.png",
  },
  "Blaster_Light_00": {
    code: "Blaster_Light_00",
    label: "ラピッドブラスター",
    innerId: 240,
    subWeapon: "Trap",
    specialWeapon: "SpTripleTornado",
    remoteImgIdent: "Path_Wst_Blaster_Light_00.png",
  },
  "Blaster_Light_01": {
    code: "Blaster_Light_01",
    label: "ラピッドブラスターデコ",
    innerId: 241,
    subWeapon: "Bomb_Torpedo",
    specialWeapon: "SpJetpack",
    remoteImgIdent: "Path_Wst_Blaster_Light_01.png",
  },
  "Blaster_Long_00": {
    code: "Blaster_Long_00",
    label: "ロングブラスター",
    innerId: 220,
    subWeapon: "Bomb_Suction",
    specialWeapon: "SpShockSonar",
    remoteImgIdent: "Path_Wst_Blaster_Long_00.png",
  },
  "Blaster_Middle_00": {
    code: "Blaster_Middle_00",
    label: "ホットブラスター",
    innerId: 210,
    subWeapon: "Bomb_Robot",
    specialWeapon: "SpGreatBarrier",
    remoteImgIdent: "Path_Wst_Blaster_Middle_00.png",
  },
  "Blaster_Middle_01": {
    code: "Blaster_Middle_01",
    label: "ホットブラスターカスタム",
    innerId: 211,
    subWeapon: "PointSensor",
    specialWeapon: "SpPogo",
    remoteImgIdent: "Path_Wst_Blaster_Middle_01.png",
  },
  "Blaster_Precision_00": {
    code: "Blaster_Precision_00",
    label: "S-BLAST92",
    innerId: 260,
    subWeapon: "Sprinkler",
    specialWeapon: "SpSkewer",
    remoteImgIdent: "Path_Wst_Blaster_Precision_00.png",
  },
  "Blaster_Precision_01": {
    code: "Blaster_Precision_01",
    label: "S-BLAST91",
    innerId: 261,
    subWeapon: "Bomb_Quick",
    specialWeapon: "SpNiceBall",
    remoteImgIdent: "Path_Wst_Blaster_Precision_01.png",
  },
  "Blaster_Short_00": {
    code: "Blaster_Short_00",
    label: "ノヴァブラスター",
    innerId: 200,
    subWeapon: "Bomb_Splash",
    specialWeapon: "SpSuperHook",
    remoteImgIdent: "Path_Wst_Blaster_Short_00.png",
  },
  "Blaster_Short_01": {
    code: "Blaster_Short_01",
    label: "ノヴァブラスターネオ",
    innerId: 201,
    subWeapon: "Bomb_Fizzy",
    specialWeapon: "SpUltraStamp",
    remoteImgIdent: "Path_Wst_Blaster_Short_01.png",
  },
  "Brush_Heavy_00": {
    code: "Brush_Heavy_00",
    label: "フィンセント",
    innerId: 1120,
    subWeapon: "Bomb_Curling",
    specialWeapon: "SpShockSonar",
    remoteImgIdent: "Path_Wst_Brush_Heavy_00.png",
  },
  "Brush_Heavy_01": {
    code: "Brush_Heavy_01",
    label: "フィンセント・ヒュー",
    innerId: 1121,
    subWeapon: "PointSensor",
    specialWeapon: "SpMultiMissile",
    remoteImgIdent: "Path_Wst_Brush_Heavy_01.png",
  },
  "Brush_Mini_00": {
    code: "Brush_Mini_00",
    label: "パブロ",
    innerId: 1100,
    subWeapon: "Bomb_Splash",
    specialWeapon: "SpMicroLaser",
    remoteImgIdent: "Path_Wst_Brush_Mini_00.png",
  },
  "Brush_Mini_01": {
    code: "Brush_Mini_01",
    label: "パブロ・ヒュー",
    innerId: 1101,
    subWeapon: "Trap",
    specialWeapon: "SpUltraStamp",
    remoteImgIdent: "Path_Wst_Brush_Mini_01.png",
  },
  "Brush_Normal_00": {
    code: "Brush_Normal_00",
    label: "ホクサイ",
    innerId: 1110,
    subWeapon: "Bomb_Suction",
    specialWeapon: "SpSuperHook",
    remoteImgIdent: "Path_Wst_Brush_Normal_00.png",
  },
  "Brush_Normal_01": {
    code: "Brush_Normal_01",
    label: "ホクサイ・ヒュー",
    innerId: 1111,
    subWeapon: "Beacon",
    specialWeapon: "SpInkStorm",
    remoteImgIdent: "Path_Wst_Brush_Normal_01.png",
  },
  "Charger_Keeper_00": {
    code: "Charger_Keeper_00",
    label: "ソイチューバー",
    innerId: 2060,
    subWeapon: "Bomb_Torpedo",
    specialWeapon: "SpMultiMissile",
    remoteImgIdent: "Path_Wst_Charger_Keeper_00.png",
  },
  "Charger_Keeper_01": {
    code: "Charger_Keeper_01",
    label: "ソイチューバーカスタム",
    innerId: 2061,
    subWeapon: "Bomb_Fizzy",
    specialWeapon: "SpUltraStamp",
    remoteImgIdent: "Path_Wst_Charger_Keeper_01.png",
  },
  "Charger_Light_00": {
    code: "Charger_Light_00",
    label: "14式竹筒銃・甲",
    innerId: 2050,
    subWeapon: "Bomb_Robot",
    specialWeapon: "SpMicroLaser",
    remoteImgIdent: "Path_Wst_Charger_Light_00.png",
  },
  "Charger_LongScope_00": {
    code: "Charger_LongScope_00",
    label: "4Kスコープ",
    innerId: 2040,
    subWeapon: "Trap",
    specialWeapon: "SpShockSonar",
    remoteImgIdent: "Path_Wst_Charger_LongScope_00.png",
  },
  "Charger_Long_00": {
    code: "Charger_Long_00",
    label: "リッター4K",
    innerId: 2030,
    subWeapon: "Trap",
    specialWeapon: "SpShockSonar",
    remoteImgIdent: "Path_Wst_Charger_Long_00.png",
  },
  "Charger_NormalScope_00": {
    code: "Charger_NormalScope_00",
    label: "スプラスコープ",
    innerId: 2020,
    subWeapon: "Bomb_Splash",
    specialWeapon: "SpBlower",
    remoteImgIdent: "Path_Wst_Charger_NormalScope_00.png",
  },
  "Charger_NormalScope_01": {
    code: "Charger_NormalScope_01",
    label: "スプラスコープコラボ",
    innerId: 2021,
    subWeapon: "Shield",
    specialWeapon: "SpTripleTornado",
    remoteImgIdent: "Path_Wst_Charger_NormalScope_01.png",
  },
  "Charger_Normal_00": {
    code: "Charger_Normal_00",
    label: "スプラチャージャー",
    innerId: 2010,
    subWeapon: "Bomb_Splash",
    specialWeapon: "SpBlower",
    remoteImgIdent: "Path_Wst_Charger_Normal_00.png",
  },
  "Charger_Normal_01": {
    code: "Charger_Normal_01",
    label: "スプラチャージャーコラボ",
    innerId: 2011,
    subWeapon: "Shield",
    specialWeapon: "SpTripleTornado",
    remoteImgIdent: "Path_Wst_Charger_Normal_01.png",
  },
  "Charger_Pencil_00": {
    code: "Charger_Pencil_00",
    label: "R-PEN/5H",
    innerId: 2070,
    subWeapon: "Sprinkler",
    specialWeapon: "SpEnergyStand",
    remoteImgIdent: "Path_Wst_Charger_Pencil_00.png",
  },
  "Charger_Pencil_01": {
    code: "Charger_Pencil_01",
    label: "R-PEN/5B",
    innerId: 2071,
    subWeapon: "Shield",
    specialWeapon: "SpInkStorm",
    remoteImgIdent: "Path_Wst_Charger_Pencil_01.png",
  },
  "Charger_Quick_00": {
    code: "Charger_Quick_00",
    label: "スクイックリンα",
    innerId: 2000,
    subWeapon: "PointSensor",
    specialWeapon: "SpGreatBarrier",
    remoteImgIdent: "Path_Wst_Charger_Quick_00.png",
  },
  "Maneuver_Dual_00": {
    code: "Maneuver_Dual_00",
    label: "デュアルスイーパー",
    innerId: 5030,
    subWeapon: "Bomb_Splash",
    specialWeapon: "SpShockSonar",
    remoteImgIdent: "Path_Wst_Maneuver_Dual_00.png",
  },
  "Maneuver_Dual_01": {
    code: "Maneuver_Dual_01",
    label: "デュアルスイーパーカスタム",
    innerId: 5031,
    subWeapon: "Beacon",
    specialWeapon: "SpFirework",
    remoteImgIdent: "Path_Wst_Maneuver_Dual_01.png",
  },
  "Maneuver_Gallon_00": {
    code: "Maneuver_Gallon_00",
    label: "ケルビン525",
    innerId: 5020,
    subWeapon: "Shield",
    specialWeapon: "SpNiceBall",
    remoteImgIdent: "Path_Wst_Maneuver_Gallon_00.png",
  },
  "Maneuver_Normal_00": {
    code: "Maneuver_Normal_00",
    label: "スプラマニューバー",
    innerId: 5010,
    subWeapon: "Bomb_Suction",
    specialWeapon: "SpChariot",
    remoteImgIdent: "Path_Wst_Maneuver_Normal_00.png",
  },
  "Maneuver_Normal_01": {
    code: "Maneuver_Normal_01",
    label: "スプラマニューバーコラボ",
    innerId: 5011,
    subWeapon: "Bomb_Curling",
    specialWeapon: "SpPogo",
    remoteImgIdent: "Path_Wst_Maneuver_Normal_01.png",
  },
  "Maneuver_Short_00": {
    code: "Maneuver_Short_00",
    label: "スパッタリー",
    innerId: 5000,
    subWeapon: "Beacon",
    specialWeapon: "SpEnergyStand",
    remoteImgIdent: "Path_Wst_Maneuver_Short_00.png",
  },
  "Maneuver_Short_01": {
    code: "Maneuver_Short_01",
    label: "スパッタリー・ヒュー",
    innerId: 5001,
    subWeapon: "Bomb_Torpedo",
    specialWeapon: "SpSkewer",
    remoteImgIdent: "Path_Wst_Maneuver_Short_01.png",
  },
  "Maneuver_Stepper_00": {
    code: "Maneuver_Stepper_00",
    label: "クアッドホッパーブラック",
    innerId: 5040,
    subWeapon: "Bomb_Robot",
    specialWeapon: "SpSkewer",
    remoteImgIdent: "Path_Wst_Maneuver_Stepper_00.png",
  },
  "Maneuver_Stepper_01": {
    code: "Maneuver_Stepper_01",
    label: "クアッドホッパーホワイト",
    innerId: 5041,
    subWeapon: "Sprinkler",
    specialWeapon: "SpSuperHook",
    remoteImgIdent: "Path_Wst_Maneuver_Stepper_01.png",
  },
  "Roller_Compact_00": {
    code: "Roller_Compact_00",
    label: "カーボンローラー",
    innerId: 1000,
    subWeapon: "Bomb_Robot",
    specialWeapon: "SpSuperHook",
    remoteImgIdent: "Path_Wst_Roller_Compact_00.png",
  },
  "Roller_Compact_01": {
    code: "Roller_Compact_01",
    label: "カーボンローラーデコ",
    innerId: 1001,
    subWeapon: "Bomb_Quick",
    specialWeapon: "SpUltraShot",
    remoteImgIdent: "Path_Wst_Roller_Compact_01.png",
  },
  "Roller_Heavy_00": {
    code: "Roller_Heavy_00",
    label: "ダイナモローラー",
    innerId: 1020,
    subWeapon: "Sprinkler",
    specialWeapon: "SpEnergyStand",
    remoteImgIdent: "Path_Wst_Roller_Heavy_00.png",
  },
  "Roller_Heavy_01": {
    code: "Roller_Heavy_01",
    label: "ダイナモローラーテスラ",
    innerId: 1021,
    subWeapon: "Bomb_Splash",
    specialWeapon: "SpFirework",
    remoteImgIdent: "Path_Wst_Roller_Heavy_01.png",
  },
  "Roller_Hunter_00": {
    code: "Roller_Hunter_00",
    label: "ヴァリアブルローラー",
    innerId: 1030,
    subWeapon: "Trap",
    specialWeapon: "SpMultiMissile",
    remoteImgIdent: "Path_Wst_Roller_Hunter_00.png",
  },
  "Roller_Normal_00": {
    code: "Roller_Normal_00",
    label: "スプラローラー",
    innerId: 1010,
    subWeapon: "Bomb_Curling",
    specialWeapon: "SpGreatBarrier",
    remoteImgIdent: "Path_Wst_Roller_Normal_00.png",
  },
  "Roller_Normal_01": {
    code: "Roller_Normal_01",
    label: "スプラローラーコラボ",
    innerId: 1011,
    subWeapon: "Beacon",
    specialWeapon: "SpCastle",
    remoteImgIdent: "Path_Wst_Roller_Normal_01.png",
  },
  "Roller_Wide_00": {
    code: "Roller_Wide_00",
    label: "ワイドローラー",
    innerId: 1040,
    subWeapon: "Shield",
    specialWeapon: "SpBlower",
    remoteImgIdent: "Path_Wst_Roller_Wide_00.png",
  },
  "Roller_Wide_01": {
    code: "Roller_Wide_01",
    label: "ワイドローラーコラボ",
    innerId: 1041,
    subWeapon: "LineMarker",
    specialWeapon: "SpInkStorm",
    remoteImgIdent: "Path_Wst_Roller_Wide_01.png",
  },
  "Saber_Lite_00": {
    code: "Saber_Lite_00",
    label: "ドライブワイパー",
    innerId: 8010,
    subWeapon: "Bomb_Torpedo",
    specialWeapon: "SpUltraStamp",
    remoteImgIdent: "Path_Wst_Saber_Lite_00.png",
  },
  "Saber_Lite_01": {
    code: "Saber_Lite_01",
    label: "ドライブワイパーデコ",
    innerId: 8011,
    subWeapon: "Beacon",
    specialWeapon: "SpMultiMissile",
    remoteImgIdent: "Path_Wst_Saber_Lite_01.png",
  },
  "Saber_Normal_00": {
    code: "Saber_Normal_00",
    label: "ジムワイパー",
    innerId: 8000,
    subWeapon: "Bomb_Quick",
    specialWeapon: "SpSuperHook",
    remoteImgIdent: "Path_Wst_Saber_Normal_00.png",
  },
  "Saber_Normal_01": {
    code: "Saber_Normal_01",
    label: "ジムワイパー・ヒュー",
    innerId: 8001,
    subWeapon: "PoisonMist",
    specialWeapon: "SpChariot",
    remoteImgIdent: "Path_Wst_Saber_Normal_01.png",
  },
  "Shelter_Compact_00": {
    code: "Shelter_Compact_00",
    label: "スパイガジェット",
    innerId: 6020,
    subWeapon: "Trap",
    specialWeapon: "SpSkewer",
    remoteImgIdent: "Path_Wst_Shelter_Compact_00.png",
  },
  "Shelter_Compact_01": {
    code: "Shelter_Compact_01",
    label: "スパイガジェットソレーラ",
    innerId: 6021,
    subWeapon: "Bomb_Torpedo",
    specialWeapon: "SpChimney",
    remoteImgIdent: "Path_Wst_Shelter_Compact_01.png",
  },
  "Shelter_Normal_00": {
    code: "Shelter_Normal_00",
    label: "パラシェルター",
    innerId: 6000,
    subWeapon: "Sprinkler",
    specialWeapon: "SpTripleTornado",
    remoteImgIdent: "Path_Wst_Shelter_Normal_00.png",
  },
  "Shelter_Normal_01": {
    code: "Shelter_Normal_01",
    label: "パラシェルターソレーラ",
    innerId: 6001,
    subWeapon: "Bomb_Robot",
    specialWeapon: "SpJetpack",
    remoteImgIdent: "Path_Wst_Shelter_Normal_01.png",
  },
  "Shelter_Wide_00": {
    code: "Shelter_Wide_00",
    label: "キャンピングシェルター",
    innerId: 6010,
    subWeapon: "Beacon",
    specialWeapon: "SpBlower",
    remoteImgIdent: "Path_Wst_Shelter_Wide_00.png",
  },
  "Shelter_Wide_01": {
    code: "Shelter_Wide_01",
    label: "キャンピングシェルターソレーラ",
    innerId: 6011,
    subWeapon: "Trap",
    specialWeapon: "SpUltraShot",
    remoteImgIdent: "Path_Wst_Shelter_Wide_01.png",
  },
  "Shooter_Blaze_00": {
    code: "Shooter_Blaze_00",
    label: "プロモデラーMG",
    innerId: 30,
    subWeapon: "Bomb_Fizzy",
    specialWeapon: "SpSkewer",
    remoteImgIdent: "Path_Wst_Shooter_Blaze_00.png",
  },
  "Shooter_Blaze_01": {
    code: "Shooter_Blaze_01",
    label: "プロモデラーRG",
    innerId: 31,
    subWeapon: "Sprinkler",
    specialWeapon: "SpNiceBall",
    remoteImgIdent: "Path_Wst_Shooter_Blaze_01.png",
  },
  "Shooter_Expert_00": {
    code: "Shooter_Expert_00",
    label: "プライムシューター",
    innerId: 70,
    subWeapon: "LineMarker",
    specialWeapon: "SpChariot",
    remoteImgIdent: "Path_Wst_Shooter_Expert_00.png",
  },
  "Shooter_Expert_01": {
    code: "Shooter_Expert_01",
    label: "プライムシューターコラボ",
    innerId: 71,
    subWeapon: "Bomb_Suction",
    specialWeapon: "SpNiceBall",
    remoteImgIdent: "Path_Wst_Shooter_Expert_01.png",
  },
  "Shooter_First_00": {
    code: "Shooter_First_00",
    label: "わかばシューター",
    innerId: 10,
    subWeapon: "Bomb_Splash",
    specialWeapon: "SpGreatBarrier",
    remoteImgIdent: "Path_Wst_Shooter_First_00.png",
  },
  "Shooter_First_01": {
    code: "Shooter_First_01",
    label: "もみじシューター",
    innerId: 11,
    subWeapon: "Bomb_Torpedo",
    specialWeapon: "SpShockSonar",
    remoteImgIdent: "Path_Wst_Shooter_First_01.png",
  },
  "Shooter_Flash_00": {
    code: "Shooter_Flash_00",
    label: "ボトルガイザー",
    innerId: 400,
    subWeapon: "Shield",
    specialWeapon: "SpUltraShot",
    remoteImgIdent: "Path_Wst_Shooter_Flash_00.png",
  },
  "Shooter_Flash_01": {
    code: "Shooter_Flash_01",
    label: "ボトルガイザーフォイル",
    innerId: 401,
    subWeapon: "Bomb_Robot",
    specialWeapon: "SpChimney",
    remoteImgIdent: "Path_Wst_Shooter_Flash_01.png",
  },
  "Shooter_Gravity_00": {
    code: "Shooter_Gravity_00",
    label: ".52ガロン",
    innerId: 50,
    subWeapon: "Shield",
    specialWeapon: "SpMicroLaser",
    remoteImgIdent: "Path_Wst_Shooter_Gravity_00.png",
  },
  "Shooter_Heavy_00": {
    code: "Shooter_Heavy_00",
    label: ".96ガロン",
    innerId: 80,
    subWeapon: "Sprinkler",
    specialWeapon: "SpBlower",
    remoteImgIdent: "Path_Wst_Shooter_Heavy_00.png",
  },
  "Shooter_Heavy_01": {
    code: "Shooter_Heavy_01",
    label: ".96ガロンデコ",
    innerId: 81,
    subWeapon: "Shield",
    specialWeapon: "SpCastle",
    remoteImgIdent: "Path_Wst_Shooter_Heavy_01.png",
  },
  "Shooter_Long_00": {
    code: "Shooter_Long_00",
    label: "ジェットスイーパー",
    innerId: 90,
    subWeapon: "LineMarker",
    specialWeapon: "SpBlower",
    remoteImgIdent: "Path_Wst_Shooter_Long_00.png",
  },
  "Shooter_Long_01": {
    code: "Shooter_Long_01",
    label: "ジェットスイーパーカスタム",
    innerId: 91,
    subWeapon: "PoisonMist",
    specialWeapon: "SpInkStorm",
    remoteImgIdent: "Path_Wst_Shooter_Long_01.png",
  },
  "Shooter_Normal_00": {
    code: "Shooter_Normal_00",
    label: "スプラシューター",
    innerId: 40,
    subWeapon: "Bomb_Suction",
    specialWeapon: "SpUltraShot",
    remoteImgIdent: "Path_Wst_Shooter_Normal_00.png",
  },
  "Shooter_Normal_01": {
    code: "Shooter_Normal_01",
    label: "スプラシューターコラボ",
    innerId: 41,
    subWeapon: "Bomb_Splash",
    specialWeapon: "SpTripleTornado",
    remoteImgIdent: "Path_Wst_Shooter_Normal_01.png",
  },
  "Shooter_Normal_H": {
    code: "Shooter_Normal_H",
    label: "ヒーローシューター レプリカ",
    innerId: 45,
    subWeapon: "Bomb_Suction",
    specialWeapon: "SpUltraShot",
    remoteImgIdent: "Path_Wst_Shooter_Normal_H.png",
  },
  "Shooter_Precision_00": {
    code: "Shooter_Precision_00",
    label: "シャープマーカー",
    innerId: 20,
    subWeapon: "Bomb_Quick",
    specialWeapon: "SpChariot",
    remoteImgIdent: "Path_Wst_Shooter_Precision_00.png",
  },
  "Shooter_Precision_01": {
    code: "Shooter_Precision_01",
    label: "シャープマーカーネオ",
    innerId: 21,
    subWeapon: "Bomb_Suction",
    specialWeapon: "SpTripleTornado",
    remoteImgIdent: "Path_Wst_Shooter_Precision_01.png",
  },
  "Shooter_QuickLong_00": {
    code: "Shooter_QuickLong_00",
    label: "スペースシューター",
    innerId: 100,
    subWeapon: "PointSensor",
    specialWeapon: "SpMicroLaser",
    remoteImgIdent: "Path_Wst_Shooter_QuickLong_00.png",
  },
  "Shooter_QuickLong_01": {
    code: "Shooter_QuickLong_01",
    label: "スペースシューターコラボ",
    innerId: 101,
    subWeapon: "Trap",
    specialWeapon: "SpJetpack",
    remoteImgIdent: "Path_Wst_Shooter_QuickLong_01.png",
  },
  "Shooter_QuickMiddle_00": {
    code: "Shooter_QuickMiddle_00",
    label: "N-ZAP85",
    innerId: 60,
    subWeapon: "Bomb_Suction",
    specialWeapon: "SpEnergyStand",
    remoteImgIdent: "Path_Wst_Shooter_QuickMiddle_00.png",
  },
  "Shooter_QuickMiddle_01": {
    code: "Shooter_QuickMiddle_01",
    label: "N-ZAP89",
    innerId: 61,
    subWeapon: "Bomb_Robot",
    specialWeapon: "SpFirework",
    remoteImgIdent: "Path_Wst_Shooter_QuickMiddle_01.png",
  },
  "Shooter_Short_00": {
    code: "Shooter_Short_00",
    label: "ボールドマーカー",
    innerId: 0,
    subWeapon: "Bomb_Curling",
    specialWeapon: "SpUltraStamp",
    remoteImgIdent: "Path_Wst_Shooter_Short_00.png",
  },
  "Shooter_Short_01": {
    code: "Shooter_Short_01",
    label: "ボールドマーカーネオ",
    innerId: 1,
    subWeapon: "Beacon",
    specialWeapon: "SpMicroLaser",
    remoteImgIdent: "Path_Wst_Shooter_Short_01.png",
  },
  "Shooter_TripleMiddle_00": {
    code: "Shooter_TripleMiddle_00",
    label: "H3リールガン",
    innerId: 310,
    subWeapon: "PointSensor",
    specialWeapon: "SpEnergyStand",
    remoteImgIdent: "Path_Wst_Shooter_TripleMiddle_00.png",
  },
  "Shooter_TripleMiddle_01": {
    code: "Shooter_TripleMiddle_01",
    label: "H3リールガンD",
    innerId: 311,
    subWeapon: "Shield",
    specialWeapon: "SpGreatBarrier",
    remoteImgIdent: "Path_Wst_Shooter_TripleMiddle_01.png",
  },
  "Shooter_TripleQuick_00": {
    code: "Shooter_TripleQuick_00",
    label: "L3リールガン",
    innerId: 300,
    subWeapon: "Bomb_Curling",
    specialWeapon: "SpChariot",
    remoteImgIdent: "Path_Wst_Shooter_TripleQuick_00.png",
  },
  "Shooter_TripleQuick_01": {
    code: "Shooter_TripleQuick_01",
    label: "L3リールガンD",
    innerId: 301,
    subWeapon: "Bomb_Quick",
    specialWeapon: "SpUltraStamp",
    remoteImgIdent: "Path_Wst_Shooter_TripleQuick_01.png",
  },
  "Slosher_Bathtub_00": {
    code: "Slosher_Bathtub_00",
    label: "オーバーフロッシャー",
    innerId: 3030,
    subWeapon: "Sprinkler",
    specialWeapon: "SpInkStorm",
    remoteImgIdent: "Path_Wst_Slosher_Bathtub_00.png",
  },
  "Slosher_Bathtub_01": {
    code: "Slosher_Bathtub_01",
    label: "オーバーフロッシャーデコ",
    innerId: 3031,
    subWeapon: "LineMarker",
    specialWeapon: "SpCastle",
    remoteImgIdent: "Path_Wst_Slosher_Bathtub_01.png",
  },
  "Slosher_Diffusion_00": {
    code: "Slosher_Diffusion_00",
    label: "ヒッセン",
    innerId: 3010,
    subWeapon: "PoisonMist",
    specialWeapon: "SpJetpack",
    remoteImgIdent: "Path_Wst_Slosher_Diffusion_00.png",
  },
  "Slosher_Diffusion_01": {
    code: "Slosher_Diffusion_01",
    label: "ヒッセン・ヒュー",
    innerId: 3011,
    subWeapon: "Bomb_Fizzy",
    specialWeapon: "SpEnergyStand",
    remoteImgIdent: "Path_Wst_Slosher_Diffusion_01.png",
  },
  "Slosher_Double_00": {
    code: "Slosher_Double_00",
    label: "モップリン",
    innerId: 3050,
    subWeapon: "Bomb_Suction",
    specialWeapon: "SpSkewer",
    remoteImgIdent: "Path_Wst_Slosher_Double_00.png",
  },
  "Slosher_Launcher_00": {
    code: "Slosher_Launcher_00",
    label: "スクリュースロッシャー",
    innerId: 3020,
    subWeapon: "Bomb_Fizzy",
    specialWeapon: "SpNiceBall",
    remoteImgIdent: "Path_Wst_Slosher_Launcher_00.png",
  },
  "Slosher_Launcher_01": {
    code: "Slosher_Launcher_01",
    label: "スクリュースロッシャーネオ",
    innerId: 3021,
    subWeapon: "PointSensor",
    specialWeapon: "SpUltraShot",
    remoteImgIdent: "Path_Wst_Slosher_Launcher_01.png",
  },
  "Slosher_Strong_00": {
    code: "Slosher_Strong_00",
    label: "バケットスロッシャー",
    innerId: 3000,
    subWeapon: "Bomb_Splash",
    specialWeapon: "SpTripleTornado",
    remoteImgIdent: "Path_Wst_Slosher_Strong_00.png",
  },
  "Slosher_Strong_01": {
    code: "Slosher_Strong_01",
    label: "バケットスロッシャーデコ",
    innerId: 3001,
    subWeapon: "LineMarker",
    specialWeapon: "SpSuperHook",
    remoteImgIdent: "Path_Wst_Slosher_Strong_01.png",
  },
  "Slosher_Washtub_00": {
    code: "Slosher_Washtub_00",
    label: "エクスプロッシャー",
    innerId: 3040,
    subWeapon: "PointSensor",
    specialWeapon: "SpInkStorm",
    remoteImgIdent: "Path_Wst_Slosher_Washtub_00.png",
  },
  "Spinner_Downpour_00": {
    code: "Spinner_Downpour_00",
    label: "クーゲルシュライバー",
    innerId: 4030,
    subWeapon: "Bomb_Fizzy",
    specialWeapon: "SpJetpack",
    remoteImgIdent: "Path_Wst_Spinner_Downpour_00.png",
  },
  "Spinner_Downpour_01": {
    code: "Spinner_Downpour_01",
    label: "クーゲルシュライバー・ヒュー",
    innerId: 4031,
    subWeapon: "Trap",
    specialWeapon: "SpBlower",
    remoteImgIdent: "Path_Wst_Spinner_Downpour_01.png",
  },
  "Spinner_HyperShort_00": {
    code: "Spinner_HyperShort_00",
    label: "イグザミナー",
    innerId: 4050,
    subWeapon: "Bomb_Curling",
    specialWeapon: "SpEnergyStand",
    remoteImgIdent: "Path_Wst_Spinner_HyperShort_00.png",
  },
  "Spinner_Hyper_00": {
    code: "Spinner_Hyper_00",
    label: "ハイドラント",
    innerId: 4020,
    subWeapon: "Bomb_Robot",
    specialWeapon: "SpNiceBall",
    remoteImgIdent: "Path_Wst_Spinner_Hyper_00.png",
  },
  "Spinner_Quick_00": {
    code: "Spinner_Quick_00",
    label: "スプラスピナー",
    innerId: 4000,
    subWeapon: "Bomb_Quick",
    specialWeapon: "SpUltraStamp",
    remoteImgIdent: "Path_Wst_Spinner_Quick_00.png",
  },
  "Spinner_Quick_01": {
    code: "Spinner_Quick_01",
    label: "スプラスピナーコラボ",
    innerId: 4001,
    subWeapon: "PoisonMist",
    specialWeapon: "SpGreatBarrier",
    remoteImgIdent: "Path_Wst_Spinner_Quick_01.png",
  },
  "Spinner_Serein_00": {
    code: "Spinner_Serein_00",
    label: "ノーチラス47",
    innerId: 4040,
    subWeapon: "PointSensor",
    specialWeapon: "SpInkStorm",
    remoteImgIdent: "Path_Wst_Spinner_Serein_00.png",
  },
  "Spinner_Standard_00": {
    code: "Spinner_Standard_00",
    label: "バレルスピナー",
    innerId: 4010,
    subWeapon: "Sprinkler",
    specialWeapon: "SpShockSonar",
    remoteImgIdent: "Path_Wst_Spinner_Standard_00.png",
  },
  "Spinner_Standard_01": {
    code: "Spinner_Standard_01",
    label: "バレルスピナーデコ",
    innerId: 4011,
    subWeapon: "PointSensor",
    specialWeapon: "SpCastle",
    remoteImgIdent: "Path_Wst_Spinner_Standard_01.png",
  },
  "Stringer_Normal_00": {
    code: "Stringer_Normal_00",
    label: "トライストリンガー",
    innerId: 7010,
    subWeapon: "PoisonMist",
    specialWeapon: "SpMicroLaser",
    remoteImgIdent: "Path_Wst_Stringer_Normal_00.png",
  },
  "Stringer_Normal_01": {
    code: "Stringer_Normal_01",
    label: "トライストリンガーコラボ",
    innerId: 7011,
    subWeapon: "Sprinkler",
    specialWeapon: "SpFirework",
    remoteImgIdent: "Path_Wst_Stringer_Normal_01.png",
  },
  "Stringer_Short_00": {
    code: "Stringer_Short_00",
    label: "LACT-450",
    innerId: 7020,
    subWeapon: "Bomb_Curling",
    specialWeapon: "SpMultiMissile",
    remoteImgIdent: "Path_Wst_Stringer_Short_00.png",
  },
  "Stringer_Short_01": {
    code: "Stringer_Short_01",
    label: "LACT-450デコ",
    innerId: 7021,
    subWeapon: "Shield",
    specialWeapon: "SpSkewer",
    remoteImgIdent: "Path_Wst_Stringer_Short_01.png",
  },
} as const;
