// This file is auto-generated by scripts/generateConstants

export const mainsCodes = [
  "Blaster_LightLong_00", // R 블래스터 엘리트
  "Blaster_LightLong_01", // R 블래스터 엘리트 데코
  "Blaster_LightShort_00", // 크래시 블래스터
  "Blaster_LightShort_01", // 네오 크래시 블래스터
  "Blaster_Light_00", // 래피드 블래스터
  "Blaster_Light_01", // 래피드 블래스터 데코
  "Blaster_Long_00", // 롱 블래스터
  "Blaster_Long_01", // 커스텀 롱 블래스터
  "Blaster_Middle_00", // 핫 블래스터
  "Blaster_Middle_01", // 커스텀 핫 블래스터
  "Blaster_Precision_00", // S-BLAST92
  "Blaster_Precision_01", // S-BLAST91
  "Blaster_Short_00", // 노바 블래스터
  "Blaster_Short_01", // 네오 노바 블래스터
  "Blaster_Short_O", // 오더 블래스터 레플리카
  "Brush_Heavy_00", // 빈센트
  "Brush_Heavy_01", // 빈센트 휴
  "Brush_Mini_00", // 파블로
  "Brush_Mini_01", // 파블로 휴
  "Brush_Normal_00", // 호쿠사이
  "Brush_Normal_01", // 호쿠사이 휴
  "Brush_Normal_O", // 오더 브러시 레플리카
  "Charger_Keeper_00", // 소이 튜버
  "Charger_Keeper_01", // 커스텀 소이 튜버
  "Charger_Light_00", // 14식 대나무 총 갑
  "Charger_Light_01", // 14식 대나무 총 을
  "Charger_LongScope_00", // 4K 스코프
  "Charger_LongScope_01", // 커스텀 4K 스코프
  "Charger_Long_00", // 리터 4K
  "Charger_Long_01", // 커스텀 리터 4K
  "Charger_NormalScope_00", // 스플랫 스코프
  "Charger_NormalScope_01", // 스플랫 스코프 컬래버
  "Charger_Normal_00", // 스플랫 차저
  "Charger_Normal_01", // 스플랫 차저 컬래버
  "Charger_Normal_O", // 오더 차저 레플리카
  "Charger_Pencil_00", // R-PEN/5H
  "Charger_Pencil_01", // R-PEN/5B
  "Charger_Quick_00", // 스퀵 클린 α
  "Charger_Quick_01", // 스퀵 클린 β
  "Maneuver_Dual_00", // 듀얼 스위퍼
  "Maneuver_Dual_01", // 커스텀 듀얼 스위퍼
  "Maneuver_Gallon_00", // 켈빈 525
  "Maneuver_Gallon_01", // 켈빈 525 데코
  "Maneuver_Long_00", // 소방 FF
  "Maneuver_Long_01", // 커스텀 소방 FF
  "Maneuver_Normal_00", // 스플랫 머누버
  "Maneuver_Normal_01", // 스플랫 머누버 컬래버
  "Maneuver_Normal_O", // 오더 머누버 레플리카
  "Maneuver_Short_00", // 스퍼터리
  "Maneuver_Short_01", // 스퍼터리 휴
  "Maneuver_Stepper_00", // 블랙 쿼드 호퍼
  "Maneuver_Stepper_01", // 화이트 쿼드 호퍼
  "Roller_Compact_00", // 카본 롤러
  "Roller_Compact_01", // 카본 롤러 데코
  "Roller_Heavy_00", // 다이너모 롤러
  "Roller_Heavy_01", // 골드 다이너모 롤러
  "Roller_Hunter_00", // 베리어블 롤러
  "Roller_Hunter_01", // 포일 베리어블 롤러
  "Roller_Normal_00", // 스플랫 롤러
  "Roller_Normal_01", // 스플랫 롤러 컬래버
  "Roller_Normal_O", // 오더 롤러 레플리카
  "Roller_Wide_00", // 와이드 롤러
  "Roller_Wide_01", // 와이드 롤러 컬래버
  "Saber_Heavy_00", // 민트 덴탈 와이퍼
  "Saber_Heavy_01", // 잉크 덴탈 와이퍼
  "Saber_Lite_00", // 드라이브 와이퍼
  "Saber_Lite_01", // 드라이브 와이퍼 데코
  "Saber_Normal_00", // 사무 와이퍼
  "Saber_Normal_01", // 사무 와이퍼 휴
  "Saber_Normal_O", // 오더 와이퍼 레플리카
  "Shelter_Compact_00", // 스파이 가젯
  "Shelter_Compact_01", // 스파이 가젯 소렐라
  "Shelter_Focus_00", // 24식 도돌이 우산 갑
  "Shelter_Focus_01", // 24식 도돌이 우산 을
  "Shelter_Normal_00", // 파라 셸터
  "Shelter_Normal_01", // 파라 셸터 소렐라
  "Shelter_Normal_O", // 오더 셸터 레플리카
  "Shelter_Wide_00", // 캠핑 셸터
  "Shelter_Wide_01", // 캠핑 셸터 소렐라
  "Shooter_Blaze_00", // 프로모델러 MG
  "Shooter_Blaze_01", // 프로모델러 RG
  "Shooter_Expert_00", // 프라임 슈터
  "Shooter_Expert_01", // 프라임 슈터 컬래버
  "Shooter_First_00", // 새싹 슈터
  "Shooter_First_01", // 단풍 슈터
  "Shooter_Flash_00", // 보틀 가이저
  "Shooter_Flash_01", // 포일 보틀 가이저
  "Shooter_Gravity_00", // .52 갤런
  "Shooter_Gravity_01", // .52 갤런 데코
  "Shooter_Heavy_00", // .96 갤런
  "Shooter_Heavy_01", // .96 갤런 데코
  "Shooter_Long_00", // 제트 스위퍼
  "Shooter_Long_01", // 커스텀 제트 스위퍼
  "Shooter_Normal_00", // 스플랫 슈터
  "Shooter_Normal_01", // 스플랫 슈터 컬래버
  "Shooter_Normal_H", // 히어로 슈터 레플리카
  "Shooter_Normal_O", // 오더 슈터 레플리카
  "Shooter_Normal_Oct", // 옥타 슈터 레플리카
  "Shooter_Precision_00", // 샤프 마커
  "Shooter_Precision_01", // 네오 샤프 마커
  "Shooter_QuickLong_00", // 스페이스 슈터
  "Shooter_QuickLong_01", // 스페이스 슈터 컬래버
  "Shooter_QuickMiddle_00", // N-ZAP85
  "Shooter_QuickMiddle_01", // N-ZAP89
  "Shooter_Short_00", // 볼드 마커
  "Shooter_Short_01", // 네오 볼드 마커
  "Shooter_TripleMiddle_00", // H3 릴 건
  "Shooter_TripleMiddle_01", // H3 릴 건 D
  "Shooter_TripleQuick_00", // L3 릴 건
  "Shooter_TripleQuick_01", // L3 릴 건 D
  "Slosher_Bathtub_00", // 오버플로셔
  "Slosher_Bathtub_01", // 오버플로셔 데코
  "Slosher_Diffusion_00", // 물통
  "Slosher_Diffusion_01", // 물통 휴
  "Slosher_Double_00", // 몹 링
  "Slosher_Double_01", // 몹 링 D
  "Slosher_Launcher_00", // 스크루 슬로셔
  "Slosher_Launcher_01", // 네오 스크루 슬로셔
  "Slosher_Strong_00", // 버킷 슬로셔
  "Slosher_Strong_01", // 버킷 슬로셔 데코
  "Slosher_Strong_O", // 오더 슬로셔 레플리카
  "Slosher_Washtub_00", // 익스플로셔
  "Slosher_Washtub_01", // 커스텀 익스플로셔
  "Spinner_Downpour_00", // 쿠겔 슈라이버
  "Spinner_Downpour_01", // 쿠겔 슈라이버 휴
  "Spinner_HyperShort_00", // 이그재미너
  "Spinner_HyperShort_01", // 이그재미너 휴
  "Spinner_Hyper_00", // 하이드런트
  "Spinner_Hyper_01", // 커스텀 하이드런트
  "Spinner_Quick_00", // 스플랫 스피너
  "Spinner_Quick_01", // 스플랫 스피너 컬래버
  "Spinner_Serein_00", // 노틸러스 47
  "Spinner_Serein_01", // 노틸러스 79
  "Spinner_Standard_00", // 배럴 스피너
  "Spinner_Standard_01", // 배럴 스피너 데코
  "Spinner_Standard_O", // 오더 스피너 레플리카
  "Stringer_Explosion_00", // 플루이드 V
  "Stringer_Explosion_01", // 커스텀 플루이드 V
  "Stringer_Normal_00", // 트라이 스트링거
  "Stringer_Normal_01", // 트라이 스트링거 컬래버
  "Stringer_Normal_O", // 오더 스트링거 레플리카
  "Stringer_Short_00", // LACT-450
  "Stringer_Short_01", // LACT-450 데코
] as const;

export const mainsCodeToData = {
  "Blaster_LightLong_00": {
    "code": "Blaster_LightLong_00",
    "labels": {
      "KRko": "R 블래스터 엘리트",
      "JPja": "Rブラスターエリート",
      "USen": "Rapid Blaster Pro",
    },
    "innerId": 250,
    "subWeapon": "PoisonMist",
    "specialWeapon": "SpBlower",
    "remoteImgIdent": "Path_Wst_Blaster_LightLong_00.png",
  },
  "Blaster_LightLong_01": {
    "code": "Blaster_LightLong_01",
    "labels": {
      "KRko": "R 블래스터 엘리트 데코",
      "JPja": "Rブラスターエリートデコ",
      "USen": "Rapid Blaster Pro Deco",
    },
    "innerId": 251,
    "subWeapon": "LineMarker",
    "specialWeapon": "SpMicroLaser",
    "remoteImgIdent": "Path_Wst_Blaster_LightLong_01.png",
  },
  "Blaster_LightShort_00": {
    "code": "Blaster_LightShort_00",
    "labels": {
      "KRko": "크래시 블래스터",
      "JPja": "クラッシュブラスター",
      "USen": "Clash Blaster",
    },
    "innerId": 230,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpUltraShot",
    "remoteImgIdent": "Path_Wst_Blaster_LightShort_00.png",
  },
  "Blaster_LightShort_01": {
    "code": "Blaster_LightShort_01",
    "labels": {
      "KRko": "네오 크래시 블래스터",
      "JPja": "クラッシュブラスターネオ",
      "USen": "Clash Blaster Neo",
    },
    "innerId": 231,
    "subWeapon": "Bomb_Curling",
    "specialWeapon": "SpFirework",
    "remoteImgIdent": "Path_Wst_Blaster_LightShort_01.png",
  },
  "Blaster_Light_00": {
    "code": "Blaster_Light_00",
    "labels": {
      "KRko": "래피드 블래스터",
      "JPja": "ラピッドブラスター",
      "USen": "Rapid Blaster",
    },
    "innerId": 240,
    "subWeapon": "Trap",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Blaster_Light_00.png",
  },
  "Blaster_Light_01": {
    "code": "Blaster_Light_01",
    "labels": {
      "KRko": "래피드 블래스터 데코",
      "JPja": "ラピッドブラスターデコ",
      "USen": "Rapid Blaster Deco",
    },
    "innerId": 241,
    "subWeapon": "Bomb_Torpedo",
    "specialWeapon": "SpJetpack",
    "remoteImgIdent": "Path_Wst_Blaster_Light_01.png",
  },
  "Blaster_Long_00": {
    "code": "Blaster_Long_00",
    "labels": {
      "KRko": "롱 블래스터",
      "JPja": "ロングブラスター",
      "USen": "Range Blaster",
    },
    "innerId": 220,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpShockSonar",
    "remoteImgIdent": "Path_Wst_Blaster_Long_00.png",
  },
  "Blaster_Long_01": {
    "code": "Blaster_Long_01",
    "labels": {
      "KRko": "커스텀 롱 블래스터",
      "JPja": "ロングブラスターカスタム",
      "USen": "Custom Range Blaster",
    },
    "innerId": 221,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpCastle",
    "remoteImgIdent": "Path_Wst_Blaster_Long_01.png",
  },
  "Blaster_Middle_00": {
    "code": "Blaster_Middle_00",
    "labels": {
      "KRko": "핫 블래스터",
      "JPja": "ホットブラスター",
      "USen": "Blaster",
    },
    "innerId": 210,
    "subWeapon": "Bomb_Robot",
    "specialWeapon": "SpGreatBarrier",
    "remoteImgIdent": "Path_Wst_Blaster_Middle_00.png",
  },
  "Blaster_Middle_01": {
    "code": "Blaster_Middle_01",
    "labels": {
      "KRko": "커스텀 핫 블래스터",
      "JPja": "ホットブラスターカスタム",
      "USen": "Custom Blaster",
    },
    "innerId": 211,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpPogo",
    "remoteImgIdent": "Path_Wst_Blaster_Middle_01.png",
  },
  "Blaster_Precision_00": {
    "code": "Blaster_Precision_00",
    "labels": {
      "KRko": "S-BLAST92",
      "JPja": "S-BLAST92",
      "USen": "S-BLAST '92",
    },
    "innerId": 260,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpSkewer",
    "remoteImgIdent": "Path_Wst_Blaster_Precision_00.png",
  },
  "Blaster_Precision_01": {
    "code": "Blaster_Precision_01",
    "labels": {
      "KRko": "S-BLAST91",
      "JPja": "S-BLAST91",
      "USen": "S-BLAST '91",
    },
    "innerId": 261,
    "subWeapon": "Bomb_Quick",
    "specialWeapon": "SpNiceBall",
    "remoteImgIdent": "Path_Wst_Blaster_Precision_01.png",
  },
  "Blaster_Short_00": {
    "code": "Blaster_Short_00",
    "labels": {
      "KRko": "노바 블래스터",
      "JPja": "ノヴァブラスター",
      "USen": "Luna Blaster",
    },
    "innerId": 200,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpSuperHook",
    "remoteImgIdent": "Path_Wst_Blaster_Short_00.png",
  },
  "Blaster_Short_01": {
    "code": "Blaster_Short_01",
    "labels": {
      "KRko": "네오 노바 블래스터",
      "JPja": "ノヴァブラスターネオ",
      "USen": "Luna Blaster Neo",
    },
    "innerId": 201,
    "subWeapon": "Bomb_Fizzy",
    "specialWeapon": "SpUltraStamp",
    "remoteImgIdent": "Path_Wst_Blaster_Short_01.png",
  },
  "Blaster_Short_O": {
    "code": "Blaster_Short_O",
    "labels": {
      "KRko": "오더 블래스터 레플리카",
      "JPja": "オーダーブラスター レプリカ",
      "USen": "Order Blaster Replica",
    },
    "innerId": 205,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpSuperHook",
    "remoteImgIdent": "Path_Wst_Blaster_Short_O.png",
  },
  "Brush_Heavy_00": {
    "code": "Brush_Heavy_00",
    "labels": { "KRko": "빈센트", "JPja": "フィンセント", "USen": "Painbrush" },
    "innerId": 1120,
    "subWeapon": "Bomb_Curling",
    "specialWeapon": "SpShockSonar",
    "remoteImgIdent": "Path_Wst_Brush_Heavy_00.png",
  },
  "Brush_Heavy_01": {
    "code": "Brush_Heavy_01",
    "labels": {
      "KRko": "빈센트 휴",
      "JPja": "フィンセント・ヒュー",
      "USen": "Painbrush Nouveau",
    },
    "innerId": 1121,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpMultiMissile",
    "remoteImgIdent": "Path_Wst_Brush_Heavy_01.png",
  },
  "Brush_Mini_00": {
    "code": "Brush_Mini_00",
    "labels": { "KRko": "파블로", "JPja": "パブロ", "USen": "Inkbrush" },
    "innerId": 1100,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpMicroLaser",
    "remoteImgIdent": "Path_Wst_Brush_Mini_00.png",
  },
  "Brush_Mini_01": {
    "code": "Brush_Mini_01",
    "labels": {
      "KRko": "파블로 휴",
      "JPja": "パブロ・ヒュー",
      "USen": "Inkbrush Nouveau",
    },
    "innerId": 1101,
    "subWeapon": "Trap",
    "specialWeapon": "SpUltraStamp",
    "remoteImgIdent": "Path_Wst_Brush_Mini_01.png",
  },
  "Brush_Normal_00": {
    "code": "Brush_Normal_00",
    "labels": { "KRko": "호쿠사이", "JPja": "ホクサイ", "USen": "Octobrush" },
    "innerId": 1110,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpSuperHook",
    "remoteImgIdent": "Path_Wst_Brush_Normal_00.png",
  },
  "Brush_Normal_01": {
    "code": "Brush_Normal_01",
    "labels": {
      "KRko": "호쿠사이 휴",
      "JPja": "ホクサイ・ヒュー",
      "USen": "Octobrush Nouveau",
    },
    "innerId": 1111,
    "subWeapon": "Beacon",
    "specialWeapon": "SpInkStorm",
    "remoteImgIdent": "Path_Wst_Brush_Normal_01.png",
  },
  "Brush_Normal_O": {
    "code": "Brush_Normal_O",
    "labels": {
      "KRko": "오더 브러시 레플리카",
      "JPja": "オーダーブラシ レプリカ",
      "USen": "Orderbrush Replica",
    },
    "innerId": 1115,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpSuperHook",
    "remoteImgIdent": "Path_Wst_Brush_Normal_O.png",
  },
  "Charger_Keeper_00": {
    "code": "Charger_Keeper_00",
    "labels": {
      "KRko": "소이 튜버",
      "JPja": "ソイチューバー",
      "USen": "Goo Tuber",
    },
    "innerId": 2060,
    "subWeapon": "Bomb_Torpedo",
    "specialWeapon": "SpMultiMissile",
    "remoteImgIdent": "Path_Wst_Charger_Keeper_00.png",
  },
  "Charger_Keeper_01": {
    "code": "Charger_Keeper_01",
    "labels": {
      "KRko": "커스텀 소이 튜버",
      "JPja": "ソイチューバーカスタム",
      "USen": "Custom Goo Tuber",
    },
    "innerId": 2061,
    "subWeapon": "Bomb_Fizzy",
    "specialWeapon": "SpUltraStamp",
    "remoteImgIdent": "Path_Wst_Charger_Keeper_01.png",
  },
  "Charger_Light_00": {
    "code": "Charger_Light_00",
    "labels": {
      "KRko": "14식 대나무 총 갑",
      "JPja": "14式竹筒銃・甲",
      "USen": "Bamboozler 14 Mk I",
    },
    "innerId": 2050,
    "subWeapon": "Bomb_Robot",
    "specialWeapon": "SpMicroLaser",
    "remoteImgIdent": "Path_Wst_Charger_Light_00.png",
  },
  "Charger_Light_01": {
    "code": "Charger_Light_01",
    "labels": {
      "KRko": "14식 대나무 총 을",
      "JPja": "14式竹筒銃・乙",
      "USen": "Bamboozler 14 Mk II",
    },
    "innerId": 2051,
    "subWeapon": "Bomb_Fizzy",
    "specialWeapon": "SpFirework",
    "remoteImgIdent": "Path_Wst_Charger_Light_01.png",
  },
  "Charger_LongScope_00": {
    "code": "Charger_LongScope_00",
    "labels": {
      "KRko": "4K 스코프",
      "JPja": "4Kスコープ",
      "USen": "E-liter 4K Scope",
    },
    "innerId": 2040,
    "subWeapon": "Trap",
    "specialWeapon": "SpShockSonar",
    "remoteImgIdent": "Path_Wst_Charger_LongScope_00.png",
  },
  "Charger_LongScope_01": {
    "code": "Charger_LongScope_01",
    "labels": {
      "KRko": "커스텀 4K 스코프",
      "JPja": "4Kスコープカスタム",
      "USen": "Custom E-liter 4K Scope",
    },
    "innerId": 2041,
    "subWeapon": "Beacon",
    "specialWeapon": "SpCastle",
    "remoteImgIdent": "Path_Wst_Charger_LongScope_01.png",
  },
  "Charger_Long_00": {
    "code": "Charger_Long_00",
    "labels": { "KRko": "리터 4K", "JPja": "リッター4K", "USen": "E-liter 4K" },
    "innerId": 2030,
    "subWeapon": "Trap",
    "specialWeapon": "SpShockSonar",
    "remoteImgIdent": "Path_Wst_Charger_Long_00.png",
  },
  "Charger_Long_01": {
    "code": "Charger_Long_01",
    "labels": {
      "KRko": "커스텀 리터 4K",
      "JPja": "リッター4Kカスタム",
      "USen": "Custom E-liter 4K",
    },
    "innerId": 2031,
    "subWeapon": "Beacon",
    "specialWeapon": "SpCastle",
    "remoteImgIdent": "Path_Wst_Charger_Long_01.png",
  },
  "Charger_NormalScope_00": {
    "code": "Charger_NormalScope_00",
    "labels": {
      "KRko": "스플랫 스코프",
      "JPja": "スプラスコープ",
      "USen": "Splatterscope",
    },
    "innerId": 2020,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpBlower",
    "remoteImgIdent": "Path_Wst_Charger_NormalScope_00.png",
  },
  "Charger_NormalScope_01": {
    "code": "Charger_NormalScope_01",
    "labels": {
      "KRko": "스플랫 스코프 컬래버",
      "JPja": "スプラスコープコラボ",
      "USen": "Z+F Splatterscope",
    },
    "innerId": 2021,
    "subWeapon": "Shield",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Charger_NormalScope_01.png",
  },
  "Charger_Normal_00": {
    "code": "Charger_Normal_00",
    "labels": {
      "KRko": "스플랫 차저",
      "JPja": "スプラチャージャー",
      "USen": "Splat Charger",
    },
    "innerId": 2010,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpBlower",
    "remoteImgIdent": "Path_Wst_Charger_Normal_00.png",
  },
  "Charger_Normal_01": {
    "code": "Charger_Normal_01",
    "labels": {
      "KRko": "스플랫 차저 컬래버",
      "JPja": "スプラチャージャーコラボ",
      "USen": "Z+F Splat Charger",
    },
    "innerId": 2011,
    "subWeapon": "Shield",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Charger_Normal_01.png",
  },
  "Charger_Normal_O": {
    "code": "Charger_Normal_O",
    "labels": {
      "KRko": "오더 차저 레플리카",
      "JPja": "オーダーチャージャー レプリカ",
      "USen": "Order Charger Replica",
    },
    "innerId": 2015,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpBlower",
    "remoteImgIdent": "Path_Wst_Charger_Normal_O.png",
  },
  "Charger_Pencil_00": {
    "code": "Charger_Pencil_00",
    "labels": {
      "KRko": "R-PEN/5H",
      "JPja": "R-PEN/5H",
      "USen": "Snipewriter 5H",
    },
    "innerId": 2070,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpEnergyStand",
    "remoteImgIdent": "Path_Wst_Charger_Pencil_00.png",
  },
  "Charger_Pencil_01": {
    "code": "Charger_Pencil_01",
    "labels": {
      "KRko": "R-PEN/5B",
      "JPja": "R-PEN/5B",
      "USen": "Snipewriter 5B",
    },
    "innerId": 2071,
    "subWeapon": "Shield",
    "specialWeapon": "SpInkStorm",
    "remoteImgIdent": "Path_Wst_Charger_Pencil_01.png",
  },
  "Charger_Quick_00": {
    "code": "Charger_Quick_00",
    "labels": {
      "KRko": "스퀵 클린 α",
      "JPja": "スクイックリンα",
      "USen": "Classic Squiffer",
    },
    "innerId": 2000,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpGreatBarrier",
    "remoteImgIdent": "Path_Wst_Charger_Quick_00.png",
  },
  "Charger_Quick_01": {
    "code": "Charger_Quick_01",
    "labels": {
      "KRko": "스퀵 클린 β",
      "JPja": "スクイックリンβ",
      "USen": "New Squiffer",
    },
    "innerId": 2001,
    "subWeapon": "Bomb_Robot",
    "specialWeapon": "SpSuperHook",
    "remoteImgIdent": "Path_Wst_Charger_Quick_01.png",
  },
  "Maneuver_Dual_00": {
    "code": "Maneuver_Dual_00",
    "labels": {
      "KRko": "듀얼 스위퍼",
      "JPja": "デュアルスイーパー",
      "USen": "Dualie Squelchers",
    },
    "innerId": 5030,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpShockSonar",
    "remoteImgIdent": "Path_Wst_Maneuver_Dual_00.png",
  },
  "Maneuver_Dual_01": {
    "code": "Maneuver_Dual_01",
    "labels": {
      "KRko": "커스텀 듀얼 스위퍼",
      "JPja": "デュアルスイーパーカスタム",
      "USen": "Custom Dualie Squelchers",
    },
    "innerId": 5031,
    "subWeapon": "Beacon",
    "specialWeapon": "SpFirework",
    "remoteImgIdent": "Path_Wst_Maneuver_Dual_01.png",
  },
  "Maneuver_Gallon_00": {
    "code": "Maneuver_Gallon_00",
    "labels": {
      "KRko": "켈빈 525",
      "JPja": "ケルビン525",
      "USen": "Glooga Dualies",
    },
    "innerId": 5020,
    "subWeapon": "Shield",
    "specialWeapon": "SpNiceBall",
    "remoteImgIdent": "Path_Wst_Maneuver_Gallon_00.png",
  },
  "Maneuver_Gallon_01": {
    "code": "Maneuver_Gallon_01",
    "labels": {
      "KRko": "켈빈 525 데코",
      "JPja": "ケルビン525デコ",
      "USen": "Glooga Dualies Deco",
    },
    "innerId": 5021,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpUltraShot",
    "remoteImgIdent": "Path_Wst_Maneuver_Gallon_01.png",
  },
  "Maneuver_Long_00": {
    "code": "Maneuver_Long_00",
    "labels": {
      "KRko": "소방 FF",
      "JPja": "ガエンFF",
      "USen": "Douser Dualies FF",
    },
    "innerId": 5050,
    "subWeapon": "Trap",
    "specialWeapon": "SpMicroLaser",
    "remoteImgIdent": "Path_Wst_Maneuver_Long_00.png",
  },
  "Maneuver_Long_01": {
    "code": "Maneuver_Long_01",
    "labels": {
      "KRko": "커스텀 소방 FF",
      "JPja": "ガエンFFカスタム",
      "USen": "Custom Douser Dualies FF",
    },
    "innerId": 5051,
    "subWeapon": "Bomb_Quick",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Maneuver_Long_01.png",
  },
  "Maneuver_Normal_00": {
    "code": "Maneuver_Normal_00",
    "labels": {
      "KRko": "스플랫 머누버",
      "JPja": "スプラマニューバー",
      "USen": "Splat Dualies",
    },
    "innerId": 5010,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpChariot",
    "remoteImgIdent": "Path_Wst_Maneuver_Normal_00.png",
  },
  "Maneuver_Normal_01": {
    "code": "Maneuver_Normal_01",
    "labels": {
      "KRko": "스플랫 머누버 컬래버",
      "JPja": "スプラマニューバーコラボ",
      "USen": "Enperry Splat Dualies",
    },
    "innerId": 5011,
    "subWeapon": "Bomb_Curling",
    "specialWeapon": "SpPogo",
    "remoteImgIdent": "Path_Wst_Maneuver_Normal_01.png",
  },
  "Maneuver_Normal_O": {
    "code": "Maneuver_Normal_O",
    "labels": {
      "KRko": "오더 머누버 레플리카",
      "JPja": "オーダーマニューバー レプリカ",
      "USen": "Order Dualie Replicas",
    },
    "innerId": 5015,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpChariot",
    "remoteImgIdent": "Path_Wst_Maneuver_Normal_O.png",
  },
  "Maneuver_Short_00": {
    "code": "Maneuver_Short_00",
    "labels": {
      "KRko": "스퍼터리",
      "JPja": "スパッタリー",
      "USen": "Dapple Dualies",
    },
    "innerId": 5000,
    "subWeapon": "Beacon",
    "specialWeapon": "SpEnergyStand",
    "remoteImgIdent": "Path_Wst_Maneuver_Short_00.png",
  },
  "Maneuver_Short_01": {
    "code": "Maneuver_Short_01",
    "labels": {
      "KRko": "스퍼터리 휴",
      "JPja": "スパッタリー・ヒュー",
      "USen": "Dapple Dualies Nouveau",
    },
    "innerId": 5001,
    "subWeapon": "Bomb_Torpedo",
    "specialWeapon": "SpSkewer",
    "remoteImgIdent": "Path_Wst_Maneuver_Short_01.png",
  },
  "Maneuver_Stepper_00": {
    "code": "Maneuver_Stepper_00",
    "labels": {
      "KRko": "블랙 쿼드 호퍼",
      "JPja": "クアッドホッパーブラック",
      "USen": "Dark Tetra Dualies",
    },
    "innerId": 5040,
    "subWeapon": "Bomb_Robot",
    "specialWeapon": "SpSkewer",
    "remoteImgIdent": "Path_Wst_Maneuver_Stepper_00.png",
  },
  "Maneuver_Stepper_01": {
    "code": "Maneuver_Stepper_01",
    "labels": {
      "KRko": "화이트 쿼드 호퍼",
      "JPja": "クアッドホッパーホワイト",
      "USen": "Light Tetra Dualies",
    },
    "innerId": 5041,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpSuperHook",
    "remoteImgIdent": "Path_Wst_Maneuver_Stepper_01.png",
  },
  "Roller_Compact_00": {
    "code": "Roller_Compact_00",
    "labels": {
      "KRko": "카본 롤러",
      "JPja": "カーボンローラー",
      "USen": "Carbon Roller",
    },
    "innerId": 1000,
    "subWeapon": "Bomb_Robot",
    "specialWeapon": "SpSuperHook",
    "remoteImgIdent": "Path_Wst_Roller_Compact_00.png",
  },
  "Roller_Compact_01": {
    "code": "Roller_Compact_01",
    "labels": {
      "KRko": "카본 롤러 데코",
      "JPja": "カーボンローラーデコ",
      "USen": "Carbon Roller Deco",
    },
    "innerId": 1001,
    "subWeapon": "Bomb_Quick",
    "specialWeapon": "SpUltraShot",
    "remoteImgIdent": "Path_Wst_Roller_Compact_01.png",
  },
  "Roller_Heavy_00": {
    "code": "Roller_Heavy_00",
    "labels": {
      "KRko": "다이너모 롤러",
      "JPja": "ダイナモローラー",
      "USen": "Dynamo Roller",
    },
    "innerId": 1020,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpEnergyStand",
    "remoteImgIdent": "Path_Wst_Roller_Heavy_00.png",
  },
  "Roller_Heavy_01": {
    "code": "Roller_Heavy_01",
    "labels": {
      "KRko": "골드 다이너모 롤러",
      "JPja": "ダイナモローラーテスラ",
      "USen": "Gold Dynamo Roller",
    },
    "innerId": 1021,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpFirework",
    "remoteImgIdent": "Path_Wst_Roller_Heavy_01.png",
  },
  "Roller_Hunter_00": {
    "code": "Roller_Hunter_00",
    "labels": {
      "KRko": "베리어블 롤러",
      "JPja": "ヴァリアブルローラー",
      "USen": "Flingza Roller",
    },
    "innerId": 1030,
    "subWeapon": "Trap",
    "specialWeapon": "SpMultiMissile",
    "remoteImgIdent": "Path_Wst_Roller_Hunter_00.png",
  },
  "Roller_Hunter_01": {
    "code": "Roller_Hunter_01",
    "labels": {
      "KRko": "포일 베리어블 롤러",
      "JPja": "ヴァリアブルローラーフォイル",
      "USen": "Foil Flingza Roller",
    },
    "innerId": 1031,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpChimney",
    "remoteImgIdent": "Path_Wst_Roller_Hunter_01.png",
  },
  "Roller_Normal_00": {
    "code": "Roller_Normal_00",
    "labels": {
      "KRko": "스플랫 롤러",
      "JPja": "スプラローラー",
      "USen": "Splat Roller",
    },
    "innerId": 1010,
    "subWeapon": "Bomb_Curling",
    "specialWeapon": "SpGreatBarrier",
    "remoteImgIdent": "Path_Wst_Roller_Normal_00.png",
  },
  "Roller_Normal_01": {
    "code": "Roller_Normal_01",
    "labels": {
      "KRko": "스플랫 롤러 컬래버",
      "JPja": "スプラローラーコラボ",
      "USen": "Krak-On Splat Roller",
    },
    "innerId": 1011,
    "subWeapon": "Beacon",
    "specialWeapon": "SpCastle",
    "remoteImgIdent": "Path_Wst_Roller_Normal_01.png",
  },
  "Roller_Normal_O": {
    "code": "Roller_Normal_O",
    "labels": {
      "KRko": "오더 롤러 레플리카",
      "JPja": "オーダーローラー レプリカ",
      "USen": "Order Roller Replica",
    },
    "innerId": 1015,
    "subWeapon": "Bomb_Curling",
    "specialWeapon": "SpGreatBarrier",
    "remoteImgIdent": "Path_Wst_Roller_Normal_O.png",
  },
  "Roller_Wide_00": {
    "code": "Roller_Wide_00",
    "labels": {
      "KRko": "와이드 롤러",
      "JPja": "ワイドローラー",
      "USen": "Big Swig Roller",
    },
    "innerId": 1040,
    "subWeapon": "Shield",
    "specialWeapon": "SpBlower",
    "remoteImgIdent": "Path_Wst_Roller_Wide_00.png",
  },
  "Roller_Wide_01": {
    "code": "Roller_Wide_01",
    "labels": {
      "KRko": "와이드 롤러 컬래버",
      "JPja": "ワイドローラーコラボ",
      "USen": "Big Swig Roller Express",
    },
    "innerId": 1041,
    "subWeapon": "LineMarker",
    "specialWeapon": "SpInkStorm",
    "remoteImgIdent": "Path_Wst_Roller_Wide_01.png",
  },
  "Saber_Heavy_00": {
    "code": "Saber_Heavy_00",
    "labels": {
      "KRko": "민트 덴탈 와이퍼",
      "JPja": "デンタルワイパーミント",
      "USen": "Mint Decavitator",
    },
    "innerId": 8020,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpGreatBarrier",
    "remoteImgIdent": "Path_Wst_Saber_Heavy_00.png",
  },
  "Saber_Heavy_01": {
    "code": "Saber_Heavy_01",
    "labels": {
      "KRko": "잉크 덴탈 와이퍼",
      "JPja": "デンタルワイパースミ",
      "USen": "Charcoal Decavitator",
    },
    "innerId": 8021,
    "subWeapon": "Shield",
    "specialWeapon": "SpJetpack",
    "remoteImgIdent": "Path_Wst_Saber_Heavy_01.png",
  },
  "Saber_Lite_00": {
    "code": "Saber_Lite_00",
    "labels": {
      "KRko": "드라이브 와이퍼",
      "JPja": "ドライブワイパー",
      "USen": "Splatana Wiper",
    },
    "innerId": 8010,
    "subWeapon": "Bomb_Torpedo",
    "specialWeapon": "SpUltraStamp",
    "remoteImgIdent": "Path_Wst_Saber_Lite_00.png",
  },
  "Saber_Lite_01": {
    "code": "Saber_Lite_01",
    "labels": {
      "KRko": "드라이브 와이퍼 데코",
      "JPja": "ドライブワイパーデコ",
      "USen": "Splatana Wiper Deco",
    },
    "innerId": 8011,
    "subWeapon": "Beacon",
    "specialWeapon": "SpMultiMissile",
    "remoteImgIdent": "Path_Wst_Saber_Lite_01.png",
  },
  "Saber_Normal_00": {
    "code": "Saber_Normal_00",
    "labels": {
      "KRko": "사무 와이퍼",
      "JPja": "ジムワイパー",
      "USen": "Splatana Stamper",
    },
    "innerId": 8000,
    "subWeapon": "Bomb_Quick",
    "specialWeapon": "SpSuperHook",
    "remoteImgIdent": "Path_Wst_Saber_Normal_00.png",
  },
  "Saber_Normal_01": {
    "code": "Saber_Normal_01",
    "labels": {
      "KRko": "사무 와이퍼 휴",
      "JPja": "ジムワイパー・ヒュー",
      "USen": "Splatana Stamper Nouveau",
    },
    "innerId": 8001,
    "subWeapon": "PoisonMist",
    "specialWeapon": "SpChariot",
    "remoteImgIdent": "Path_Wst_Saber_Normal_01.png",
  },
  "Saber_Normal_O": {
    "code": "Saber_Normal_O",
    "labels": {
      "KRko": "오더 와이퍼 레플리카",
      "JPja": "オーダーワイパー レプリカ",
      "USen": "Order Splatana Replica",
    },
    "innerId": 8005,
    "subWeapon": "Bomb_Quick",
    "specialWeapon": "SpSuperHook",
    "remoteImgIdent": "Path_Wst_Saber_Normal_O.png",
  },
  "Shelter_Compact_00": {
    "code": "Shelter_Compact_00",
    "labels": {
      "KRko": "스파이 가젯",
      "JPja": "スパイガジェット",
      "USen": "Undercover Brella",
    },
    "innerId": 6020,
    "subWeapon": "Trap",
    "specialWeapon": "SpSkewer",
    "remoteImgIdent": "Path_Wst_Shelter_Compact_00.png",
  },
  "Shelter_Compact_01": {
    "code": "Shelter_Compact_01",
    "labels": {
      "KRko": "스파이 가젯 소렐라",
      "JPja": "スパイガジェットソレーラ",
      "USen": "Undercover Sorella Brella",
    },
    "innerId": 6021,
    "subWeapon": "Bomb_Torpedo",
    "specialWeapon": "SpChimney",
    "remoteImgIdent": "Path_Wst_Shelter_Compact_01.png",
  },
  "Shelter_Focus_00": {
    "code": "Shelter_Focus_00",
    "labels": {
      "KRko": "24식 도돌이 우산 갑",
      "JPja": "24式張替傘・甲",
      "USen": "Recycled Brella 24 Mk I",
    },
    "innerId": 6030,
    "subWeapon": "LineMarker",
    "specialWeapon": "SpGreatBarrier",
    "remoteImgIdent": "Path_Wst_Shelter_Focus_00.png",
  },
  "Shelter_Focus_01": {
    "code": "Shelter_Focus_01",
    "labels": {
      "KRko": "24식 도돌이 우산 을",
      "JPja": "24式張替傘・乙",
      "USen": "Recycled Brella 24 Mk II",
    },
    "innerId": 6031,
    "subWeapon": "PoisonMist",
    "specialWeapon": "SpPogo",
    "remoteImgIdent": "Path_Wst_Shelter_Focus_01.png",
  },
  "Shelter_Normal_00": {
    "code": "Shelter_Normal_00",
    "labels": {
      "KRko": "파라 셸터",
      "JPja": "パラシェルター",
      "USen": "Splat Brella",
    },
    "innerId": 6000,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Shelter_Normal_00.png",
  },
  "Shelter_Normal_01": {
    "code": "Shelter_Normal_01",
    "labels": {
      "KRko": "파라 셸터 소렐라",
      "JPja": "パラシェルターソレーラ",
      "USen": "Sorella Brella",
    },
    "innerId": 6001,
    "subWeapon": "Bomb_Robot",
    "specialWeapon": "SpJetpack",
    "remoteImgIdent": "Path_Wst_Shelter_Normal_01.png",
  },
  "Shelter_Normal_O": {
    "code": "Shelter_Normal_O",
    "labels": {
      "KRko": "오더 셸터 레플리카",
      "JPja": "オーダーシェルター レプリカ",
      "USen": "Order Brella Replica",
    },
    "innerId": 6005,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Shelter_Normal_O.png",
  },
  "Shelter_Wide_00": {
    "code": "Shelter_Wide_00",
    "labels": {
      "KRko": "캠핑 셸터",
      "JPja": "キャンピングシェルター",
      "USen": "Tenta Brella",
    },
    "innerId": 6010,
    "subWeapon": "Beacon",
    "specialWeapon": "SpBlower",
    "remoteImgIdent": "Path_Wst_Shelter_Wide_00.png",
  },
  "Shelter_Wide_01": {
    "code": "Shelter_Wide_01",
    "labels": {
      "KRko": "캠핑 셸터 소렐라",
      "JPja": "キャンピングシェルターソレーラ",
      "USen": "Tenta Sorella Brella",
    },
    "innerId": 6011,
    "subWeapon": "Trap",
    "specialWeapon": "SpUltraShot",
    "remoteImgIdent": "Path_Wst_Shelter_Wide_01.png",
  },
  "Shooter_Blaze_00": {
    "code": "Shooter_Blaze_00",
    "labels": {
      "KRko": "프로모델러 MG",
      "JPja": "プロモデラーMG",
      "USen": "Aerospray MG",
    },
    "innerId": 30,
    "subWeapon": "Bomb_Fizzy",
    "specialWeapon": "SpSkewer",
    "remoteImgIdent": "Path_Wst_Shooter_Blaze_00.png",
  },
  "Shooter_Blaze_01": {
    "code": "Shooter_Blaze_01",
    "labels": {
      "KRko": "프로모델러 RG",
      "JPja": "プロモデラーRG",
      "USen": "Aerospray RG",
    },
    "innerId": 31,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpNiceBall",
    "remoteImgIdent": "Path_Wst_Shooter_Blaze_01.png",
  },
  "Shooter_Expert_00": {
    "code": "Shooter_Expert_00",
    "labels": {
      "KRko": "프라임 슈터",
      "JPja": "プライムシューター",
      "USen": "Splattershot Pro",
    },
    "innerId": 70,
    "subWeapon": "LineMarker",
    "specialWeapon": "SpChariot",
    "remoteImgIdent": "Path_Wst_Shooter_Expert_00.png",
  },
  "Shooter_Expert_01": {
    "code": "Shooter_Expert_01",
    "labels": {
      "KRko": "프라임 슈터 컬래버",
      "JPja": "プライムシューターコラボ",
      "USen": "Forge Splattershot Pro",
    },
    "innerId": 71,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpNiceBall",
    "remoteImgIdent": "Path_Wst_Shooter_Expert_01.png",
  },
  "Shooter_First_00": {
    "code": "Shooter_First_00",
    "labels": {
      "KRko": "새싹 슈터",
      "JPja": "わかばシューター",
      "USen": "Splattershot Jr.",
    },
    "innerId": 10,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpGreatBarrier",
    "remoteImgIdent": "Path_Wst_Shooter_First_00.png",
  },
  "Shooter_First_01": {
    "code": "Shooter_First_01",
    "labels": {
      "KRko": "단풍 슈터",
      "JPja": "もみじシューター",
      "USen": "Custom Splattershot Jr.",
    },
    "innerId": 11,
    "subWeapon": "Bomb_Torpedo",
    "specialWeapon": "SpShockSonar",
    "remoteImgIdent": "Path_Wst_Shooter_First_01.png",
  },
  "Shooter_Flash_00": {
    "code": "Shooter_Flash_00",
    "labels": {
      "KRko": "보틀 가이저",
      "JPja": "ボトルガイザー",
      "USen": "Squeezer",
    },
    "innerId": 400,
    "subWeapon": "Shield",
    "specialWeapon": "SpUltraShot",
    "remoteImgIdent": "Path_Wst_Shooter_Flash_00.png",
  },
  "Shooter_Flash_01": {
    "code": "Shooter_Flash_01",
    "labels": {
      "KRko": "포일 보틀 가이저",
      "JPja": "ボトルガイザーフォイル",
      "USen": "Foil Squeezer",
    },
    "innerId": 401,
    "subWeapon": "Bomb_Robot",
    "specialWeapon": "SpChimney",
    "remoteImgIdent": "Path_Wst_Shooter_Flash_01.png",
  },
  "Shooter_Gravity_00": {
    "code": "Shooter_Gravity_00",
    "labels": { "KRko": ".52 갤런", "JPja": ".52ガロン", "USen": ".52 Gal" },
    "innerId": 50,
    "subWeapon": "Shield",
    "specialWeapon": "SpMicroLaser",
    "remoteImgIdent": "Path_Wst_Shooter_Gravity_00.png",
  },
  "Shooter_Gravity_01": {
    "code": "Shooter_Gravity_01",
    "labels": {
      "KRko": ".52 갤런 데코",
      "JPja": ".52ガロンデコ",
      "USen": ".52 Gal Deco",
    },
    "innerId": 51,
    "subWeapon": "Bomb_Curling",
    "specialWeapon": "SpChimney",
    "remoteImgIdent": "Path_Wst_Shooter_Gravity_01.png",
  },
  "Shooter_Heavy_00": {
    "code": "Shooter_Heavy_00",
    "labels": { "KRko": ".96 갤런", "JPja": ".96ガロン", "USen": ".96 Gal" },
    "innerId": 80,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpBlower",
    "remoteImgIdent": "Path_Wst_Shooter_Heavy_00.png",
  },
  "Shooter_Heavy_01": {
    "code": "Shooter_Heavy_01",
    "labels": {
      "KRko": ".96 갤런 데코",
      "JPja": ".96ガロンデコ",
      "USen": ".96 Gal Deco",
    },
    "innerId": 81,
    "subWeapon": "Shield",
    "specialWeapon": "SpCastle",
    "remoteImgIdent": "Path_Wst_Shooter_Heavy_01.png",
  },
  "Shooter_Long_00": {
    "code": "Shooter_Long_00",
    "labels": {
      "KRko": "제트 스위퍼",
      "JPja": "ジェットスイーパー",
      "USen": "Jet Squelcher",
    },
    "innerId": 90,
    "subWeapon": "LineMarker",
    "specialWeapon": "SpBlower",
    "remoteImgIdent": "Path_Wst_Shooter_Long_00.png",
  },
  "Shooter_Long_01": {
    "code": "Shooter_Long_01",
    "labels": {
      "KRko": "커스텀 제트 스위퍼",
      "JPja": "ジェットスイーパーカスタム",
      "USen": "Custom Jet Squelcher",
    },
    "innerId": 91,
    "subWeapon": "PoisonMist",
    "specialWeapon": "SpInkStorm",
    "remoteImgIdent": "Path_Wst_Shooter_Long_01.png",
  },
  "Shooter_Normal_00": {
    "code": "Shooter_Normal_00",
    "labels": {
      "KRko": "스플랫 슈터",
      "JPja": "スプラシューター",
      "USen": "Splattershot",
    },
    "innerId": 40,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpUltraShot",
    "remoteImgIdent": "Path_Wst_Shooter_Normal_00.png",
  },
  "Shooter_Normal_01": {
    "code": "Shooter_Normal_01",
    "labels": {
      "KRko": "스플랫 슈터 컬래버",
      "JPja": "スプラシューターコラボ",
      "USen": "Tentatek Splattershot",
    },
    "innerId": 41,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Shooter_Normal_01.png",
  },
  "Shooter_Normal_H": {
    "code": "Shooter_Normal_H",
    "labels": {
      "KRko": "히어로 슈터 레플리카",
      "JPja": "ヒーローシューター レプリカ",
      "USen": "Hero Shot Replica",
    },
    "innerId": 45,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpUltraShot",
    "remoteImgIdent": "Path_Wst_Shooter_Normal_H.png",
  },
  "Shooter_Normal_O": {
    "code": "Shooter_Normal_O",
    "labels": {
      "KRko": "오더 슈터 레플리카",
      "JPja": "オーダーシューター レプリカ",
      "USen": "Order Shot Replica",
    },
    "innerId": 47,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpUltraShot",
    "remoteImgIdent": "Path_Wst_Shooter_Normal_O.png",
  },
  "Shooter_Normal_Oct": {
    "code": "Shooter_Normal_Oct",
    "labels": {
      "KRko": "옥타 슈터 레플리카",
      "JPja": "オクタシューター レプリカ",
      "USen": "Octo Shot Replica",
    },
    "innerId": 46,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Shooter_Normal_Oct.png",
  },
  "Shooter_Precision_00": {
    "code": "Shooter_Precision_00",
    "labels": {
      "KRko": "샤프 마커",
      "JPja": "シャープマーカー",
      "USen": "Splash-o-matic",
    },
    "innerId": 20,
    "subWeapon": "Bomb_Quick",
    "specialWeapon": "SpChariot",
    "remoteImgIdent": "Path_Wst_Shooter_Precision_00.png",
  },
  "Shooter_Precision_01": {
    "code": "Shooter_Precision_01",
    "labels": {
      "KRko": "네오 샤프 마커",
      "JPja": "シャープマーカーネオ",
      "USen": "Neo Splash-o-matic",
    },
    "innerId": 21,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Shooter_Precision_01.png",
  },
  "Shooter_QuickLong_00": {
    "code": "Shooter_QuickLong_00",
    "labels": {
      "KRko": "스페이스 슈터",
      "JPja": "スペースシューター",
      "USen": "Splattershot Nova",
    },
    "innerId": 100,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpMicroLaser",
    "remoteImgIdent": "Path_Wst_Shooter_QuickLong_00.png",
  },
  "Shooter_QuickLong_01": {
    "code": "Shooter_QuickLong_01",
    "labels": {
      "KRko": "스페이스 슈터 컬래버",
      "JPja": "スペースシューターコラボ",
      "USen": "Annaki Splattershot Nova",
    },
    "innerId": 101,
    "subWeapon": "Trap",
    "specialWeapon": "SpJetpack",
    "remoteImgIdent": "Path_Wst_Shooter_QuickLong_01.png",
  },
  "Shooter_QuickMiddle_00": {
    "code": "Shooter_QuickMiddle_00",
    "labels": { "KRko": "N-ZAP85", "JPja": "N-ZAP85", "USen": "N-ZAP '85" },
    "innerId": 60,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpEnergyStand",
    "remoteImgIdent": "Path_Wst_Shooter_QuickMiddle_00.png",
  },
  "Shooter_QuickMiddle_01": {
    "code": "Shooter_QuickMiddle_01",
    "labels": { "KRko": "N-ZAP89", "JPja": "N-ZAP89", "USen": "N-ZAP '89" },
    "innerId": 61,
    "subWeapon": "Bomb_Robot",
    "specialWeapon": "SpFirework",
    "remoteImgIdent": "Path_Wst_Shooter_QuickMiddle_01.png",
  },
  "Shooter_Short_00": {
    "code": "Shooter_Short_00",
    "labels": {
      "KRko": "볼드 마커",
      "JPja": "ボールドマーカー",
      "USen": "Sploosh-o-matic",
    },
    "innerId": 0,
    "subWeapon": "Bomb_Curling",
    "specialWeapon": "SpUltraStamp",
    "remoteImgIdent": "Path_Wst_Shooter_Short_00.png",
  },
  "Shooter_Short_01": {
    "code": "Shooter_Short_01",
    "labels": {
      "KRko": "네오 볼드 마커",
      "JPja": "ボールドマーカーネオ",
      "USen": "Neo Sploosh-o-matic",
    },
    "innerId": 1,
    "subWeapon": "Beacon",
    "specialWeapon": "SpMicroLaser",
    "remoteImgIdent": "Path_Wst_Shooter_Short_01.png",
  },
  "Shooter_TripleMiddle_00": {
    "code": "Shooter_TripleMiddle_00",
    "labels": {
      "KRko": "H3 릴 건",
      "JPja": "H3リールガン",
      "USen": "H-3 Nozzlenose",
    },
    "innerId": 310,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpEnergyStand",
    "remoteImgIdent": "Path_Wst_Shooter_TripleMiddle_00.png",
  },
  "Shooter_TripleMiddle_01": {
    "code": "Shooter_TripleMiddle_01",
    "labels": {
      "KRko": "H3 릴 건 D",
      "JPja": "H3リールガンD",
      "USen": "H-3 Nozzlenose D",
    },
    "innerId": 311,
    "subWeapon": "Shield",
    "specialWeapon": "SpGreatBarrier",
    "remoteImgIdent": "Path_Wst_Shooter_TripleMiddle_01.png",
  },
  "Shooter_TripleQuick_00": {
    "code": "Shooter_TripleQuick_00",
    "labels": {
      "KRko": "L3 릴 건",
      "JPja": "L3リールガン",
      "USen": "L-3 Nozzlenose",
    },
    "innerId": 300,
    "subWeapon": "Bomb_Curling",
    "specialWeapon": "SpChariot",
    "remoteImgIdent": "Path_Wst_Shooter_TripleQuick_00.png",
  },
  "Shooter_TripleQuick_01": {
    "code": "Shooter_TripleQuick_01",
    "labels": {
      "KRko": "L3 릴 건 D",
      "JPja": "L3リールガンD",
      "USen": "L-3 Nozzlenose D",
    },
    "innerId": 301,
    "subWeapon": "Bomb_Quick",
    "specialWeapon": "SpUltraStamp",
    "remoteImgIdent": "Path_Wst_Shooter_TripleQuick_01.png",
  },
  "Slosher_Bathtub_00": {
    "code": "Slosher_Bathtub_00",
    "labels": {
      "KRko": "오버플로셔",
      "JPja": "オーバーフロッシャー",
      "USen": "Bloblobber",
    },
    "innerId": 3030,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpInkStorm",
    "remoteImgIdent": "Path_Wst_Slosher_Bathtub_00.png",
  },
  "Slosher_Bathtub_01": {
    "code": "Slosher_Bathtub_01",
    "labels": {
      "KRko": "오버플로셔 데코",
      "JPja": "オーバーフロッシャーデコ",
      "USen": "Bloblobber Deco",
    },
    "innerId": 3031,
    "subWeapon": "LineMarker",
    "specialWeapon": "SpCastle",
    "remoteImgIdent": "Path_Wst_Slosher_Bathtub_01.png",
  },
  "Slosher_Diffusion_00": {
    "code": "Slosher_Diffusion_00",
    "labels": { "KRko": "물통", "JPja": "ヒッセン", "USen": "Tri-Slosher" },
    "innerId": 3010,
    "subWeapon": "PoisonMist",
    "specialWeapon": "SpJetpack",
    "remoteImgIdent": "Path_Wst_Slosher_Diffusion_00.png",
  },
  "Slosher_Diffusion_01": {
    "code": "Slosher_Diffusion_01",
    "labels": {
      "KRko": "물통 휴",
      "JPja": "ヒッセン・ヒュー",
      "USen": "Tri-Slosher Nouveau",
    },
    "innerId": 3011,
    "subWeapon": "Bomb_Fizzy",
    "specialWeapon": "SpEnergyStand",
    "remoteImgIdent": "Path_Wst_Slosher_Diffusion_01.png",
  },
  "Slosher_Double_00": {
    "code": "Slosher_Double_00",
    "labels": {
      "KRko": "몹 링",
      "JPja": "モップリン",
      "USen": "Dread Wringer",
    },
    "innerId": 3050,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpSkewer",
    "remoteImgIdent": "Path_Wst_Slosher_Double_00.png",
  },
  "Slosher_Double_01": {
    "code": "Slosher_Double_01",
    "labels": {
      "KRko": "몹 링 D",
      "JPja": "モップリンD",
      "USen": "Dread Wringer D",
    },
    "innerId": 3051,
    "subWeapon": "Beacon",
    "specialWeapon": "SpShockSonar",
    "remoteImgIdent": "Path_Wst_Slosher_Double_01.png",
  },
  "Slosher_Launcher_00": {
    "code": "Slosher_Launcher_00",
    "labels": {
      "KRko": "스크루 슬로셔",
      "JPja": "スクリュースロッシャー",
      "USen": "Sloshing Machine",
    },
    "innerId": 3020,
    "subWeapon": "Bomb_Fizzy",
    "specialWeapon": "SpNiceBall",
    "remoteImgIdent": "Path_Wst_Slosher_Launcher_00.png",
  },
  "Slosher_Launcher_01": {
    "code": "Slosher_Launcher_01",
    "labels": {
      "KRko": "네오 스크루 슬로셔",
      "JPja": "スクリュースロッシャーネオ",
      "USen": "Sloshing Machine Neo",
    },
    "innerId": 3021,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpUltraShot",
    "remoteImgIdent": "Path_Wst_Slosher_Launcher_01.png",
  },
  "Slosher_Strong_00": {
    "code": "Slosher_Strong_00",
    "labels": {
      "KRko": "버킷 슬로셔",
      "JPja": "バケットスロッシャー",
      "USen": "Slosher",
    },
    "innerId": 3000,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Slosher_Strong_00.png",
  },
  "Slosher_Strong_01": {
    "code": "Slosher_Strong_01",
    "labels": {
      "KRko": "버킷 슬로셔 데코",
      "JPja": "バケットスロッシャーデコ",
      "USen": "Slosher Deco",
    },
    "innerId": 3001,
    "subWeapon": "LineMarker",
    "specialWeapon": "SpSuperHook",
    "remoteImgIdent": "Path_Wst_Slosher_Strong_01.png",
  },
  "Slosher_Strong_O": {
    "code": "Slosher_Strong_O",
    "labels": {
      "KRko": "오더 슬로셔 레플리카",
      "JPja": "オーダースロッシャー レプリカ",
      "USen": "Order Slosher Replica",
    },
    "innerId": 3005,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpTripleTornado",
    "remoteImgIdent": "Path_Wst_Slosher_Strong_O.png",
  },
  "Slosher_Washtub_00": {
    "code": "Slosher_Washtub_00",
    "labels": {
      "KRko": "익스플로셔",
      "JPja": "エクスプロッシャー",
      "USen": "Explosher",
    },
    "innerId": 3040,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpInkStorm",
    "remoteImgIdent": "Path_Wst_Slosher_Washtub_00.png",
  },
  "Slosher_Washtub_01": {
    "code": "Slosher_Washtub_01",
    "labels": {
      "KRko": "커스텀 익스플로셔",
      "JPja": "エクスプロッシャーカスタム",
      "USen": "Custom Explosher",
    },
    "innerId": 3041,
    "subWeapon": "Shield",
    "specialWeapon": "SpPogo",
    "remoteImgIdent": "Path_Wst_Slosher_Washtub_01.png",
  },
  "Spinner_Downpour_00": {
    "code": "Spinner_Downpour_00",
    "labels": {
      "KRko": "쿠겔 슈라이버",
      "JPja": "クーゲルシュライバー",
      "USen": "Ballpoint Splatling",
    },
    "innerId": 4030,
    "subWeapon": "Bomb_Fizzy",
    "specialWeapon": "SpJetpack",
    "remoteImgIdent": "Path_Wst_Spinner_Downpour_00.png",
  },
  "Spinner_Downpour_01": {
    "code": "Spinner_Downpour_01",
    "labels": {
      "KRko": "쿠겔 슈라이버 휴",
      "JPja": "クーゲルシュライバー・ヒュー",
      "USen": "Ballpoint Splatling Nouveau",
    },
    "innerId": 4031,
    "subWeapon": "Trap",
    "specialWeapon": "SpBlower",
    "remoteImgIdent": "Path_Wst_Spinner_Downpour_01.png",
  },
  "Spinner_HyperShort_00": {
    "code": "Spinner_HyperShort_00",
    "labels": {
      "KRko": "이그재미너",
      "JPja": "イグザミナー",
      "USen": "Heavy Edit Splatling",
    },
    "innerId": 4050,
    "subWeapon": "Bomb_Curling",
    "specialWeapon": "SpEnergyStand",
    "remoteImgIdent": "Path_Wst_Spinner_HyperShort_00.png",
  },
  "Spinner_HyperShort_01": {
    "code": "Spinner_HyperShort_01",
    "labels": {
      "KRko": "이그재미너 휴",
      "JPja": "イグザミナー・ヒュー",
      "USen": "Heavy Edit Splatling Nouveau",
    },
    "innerId": 4051,
    "subWeapon": "Bomb_Splash",
    "specialWeapon": "SpChariot",
    "remoteImgIdent": "Path_Wst_Spinner_HyperShort_01.png",
  },
  "Spinner_Hyper_00": {
    "code": "Spinner_Hyper_00",
    "labels": {
      "KRko": "하이드런트",
      "JPja": "ハイドラント",
      "USen": "Hydra Splatling",
    },
    "innerId": 4020,
    "subWeapon": "Bomb_Robot",
    "specialWeapon": "SpNiceBall",
    "remoteImgIdent": "Path_Wst_Spinner_Hyper_00.png",
  },
  "Spinner_Hyper_01": {
    "code": "Spinner_Hyper_01",
    "labels": {
      "KRko": "커스텀 하이드런트",
      "JPja": "ハイドラントカスタム",
      "USen": "Custom Hydra Splatling",
    },
    "innerId": 4021,
    "subWeapon": "Trap",
    "specialWeapon": "SpChimney",
    "remoteImgIdent": "Path_Wst_Spinner_Hyper_01.png",
  },
  "Spinner_Quick_00": {
    "code": "Spinner_Quick_00",
    "labels": {
      "KRko": "스플랫 스피너",
      "JPja": "スプラスピナー",
      "USen": "Mini Splatling",
    },
    "innerId": 4000,
    "subWeapon": "Bomb_Quick",
    "specialWeapon": "SpUltraStamp",
    "remoteImgIdent": "Path_Wst_Spinner_Quick_00.png",
  },
  "Spinner_Quick_01": {
    "code": "Spinner_Quick_01",
    "labels": {
      "KRko": "스플랫 스피너 컬래버",
      "JPja": "スプラスピナーコラボ",
      "USen": "Zink Mini Splatling",
    },
    "innerId": 4001,
    "subWeapon": "PoisonMist",
    "specialWeapon": "SpGreatBarrier",
    "remoteImgIdent": "Path_Wst_Spinner_Quick_01.png",
  },
  "Spinner_Serein_00": {
    "code": "Spinner_Serein_00",
    "labels": {
      "KRko": "노틸러스 47",
      "JPja": "ノーチラス47",
      "USen": "Nautilus 47",
    },
    "innerId": 4040,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpInkStorm",
    "remoteImgIdent": "Path_Wst_Spinner_Serein_00.png",
  },
  "Spinner_Serein_01": {
    "code": "Spinner_Serein_01",
    "labels": {
      "KRko": "노틸러스 79",
      "JPja": "ノーチラス79",
      "USen": "Nautilus 79",
    },
    "innerId": 4041,
    "subWeapon": "Bomb_Suction",
    "specialWeapon": "SpPogo",
    "remoteImgIdent": "Path_Wst_Spinner_Serein_01.png",
  },
  "Spinner_Standard_00": {
    "code": "Spinner_Standard_00",
    "labels": {
      "KRko": "배럴 스피너",
      "JPja": "バレルスピナー",
      "USen": "Heavy Splatling",
    },
    "innerId": 4010,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpShockSonar",
    "remoteImgIdent": "Path_Wst_Spinner_Standard_00.png",
  },
  "Spinner_Standard_01": {
    "code": "Spinner_Standard_01",
    "labels": {
      "KRko": "배럴 스피너 데코",
      "JPja": "バレルスピナーデコ",
      "USen": "Heavy Splatling Deco",
    },
    "innerId": 4011,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpCastle",
    "remoteImgIdent": "Path_Wst_Spinner_Standard_01.png",
  },
  "Spinner_Standard_O": {
    "code": "Spinner_Standard_O",
    "labels": {
      "KRko": "오더 스피너 레플리카",
      "JPja": "オーダースピナー レプリカ",
      "USen": "Order Splatling Replica",
    },
    "innerId": 4015,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpShockSonar",
    "remoteImgIdent": "Path_Wst_Spinner_Standard_O.png",
  },
  "Stringer_Explosion_00": {
    "code": "Stringer_Explosion_00",
    "labels": {
      "KRko": "플루이드 V",
      "JPja": "フルイドV",
      "USen": "Wellstring V",
    },
    "innerId": 7030,
    "subWeapon": "Bomb_Robot",
    "specialWeapon": "SpUltraStamp",
    "remoteImgIdent": "Path_Wst_Stringer_Explosion_00.png",
  },
  "Stringer_Explosion_01": {
    "code": "Stringer_Explosion_01",
    "labels": {
      "KRko": "커스텀 플루이드 V",
      "JPja": "フルイドVカスタム",
      "USen": "Custom Wellstring V",
    },
    "innerId": 7031,
    "subWeapon": "PointSensor",
    "specialWeapon": "SpShockSonar",
    "remoteImgIdent": "Path_Wst_Stringer_Explosion_01.png",
  },
  "Stringer_Normal_00": {
    "code": "Stringer_Normal_00",
    "labels": {
      "KRko": "트라이 스트링거",
      "JPja": "トライストリンガー",
      "USen": "Tri-Stringer",
    },
    "innerId": 7010,
    "subWeapon": "PoisonMist",
    "specialWeapon": "SpMicroLaser",
    "remoteImgIdent": "Path_Wst_Stringer_Normal_00.png",
  },
  "Stringer_Normal_01": {
    "code": "Stringer_Normal_01",
    "labels": {
      "KRko": "트라이 스트링거 컬래버",
      "JPja": "トライストリンガーコラボ",
      "USen": "Inkline Tri-Stringer",
    },
    "innerId": 7011,
    "subWeapon": "Sprinkler",
    "specialWeapon": "SpFirework",
    "remoteImgIdent": "Path_Wst_Stringer_Normal_01.png",
  },
  "Stringer_Normal_O": {
    "code": "Stringer_Normal_O",
    "labels": {
      "KRko": "오더 스트링거 레플리카",
      "JPja": "オーダーストリンガー レプリカ",
      "USen": "Order Stringer Replica",
    },
    "innerId": 7015,
    "subWeapon": "PoisonMist",
    "specialWeapon": "SpMicroLaser",
    "remoteImgIdent": "Path_Wst_Stringer_Normal_O.png",
  },
  "Stringer_Short_00": {
    "code": "Stringer_Short_00",
    "labels": {
      "KRko": "LACT-450",
      "JPja": "LACT-450",
      "USen": "REEF-LUX 450",
    },
    "innerId": 7020,
    "subWeapon": "Bomb_Curling",
    "specialWeapon": "SpMultiMissile",
    "remoteImgIdent": "Path_Wst_Stringer_Short_00.png",
  },
  "Stringer_Short_01": {
    "code": "Stringer_Short_01",
    "labels": {
      "KRko": "LACT-450 데코",
      "JPja": "LACT-450デコ",
      "USen": "REEF-LUX 450 Deco",
    },
    "innerId": 7021,
    "subWeapon": "Shield",
    "specialWeapon": "SpSkewer",
    "remoteImgIdent": "Path_Wst_Stringer_Short_01.png",
  },
} as const;
