// This file is auto-generated by scripts/generateConstants

export const codes = [
  "SpBlower", // 흡입기
  "SpCastle", // 로열 크라켄
  "SpChariot", // 크랩 탱크
  "SpChimney", // 스플래터컬러 스크린
  "SpEnergyStand", // 에너지 스탠드
  "SpFirework", // 디코이 캐넌
  "SpGreatBarrier", // 그레이트 배리어
  "SpInkStorm", // 먹구름
  "SpJetpack", // 제트 팩
  "SpMicroLaser", // 메가폰 레이저 5.1ch
  "SpMultiMissile", // 멀티 미사일
  "SpNiceBall", // 나이스옥
  "SpPogo", // 울트라 착지
  "SpShockSonar", // 홉 소나
  "SpSkewer", // 샤크 라이드
  "SpSuperHook", // 쇼크 원더
  "SpTripleTornado", // 트리플 토네이도
  "SpUltraShot", // 울트라 샷
  "SpUltraStamp", // 울트라 스탬프
] as const;

export const codeToData = {
  "SpBlower": {
    "code": "SpBlower",
    "labels": { "KRko": "흡입기", "JPja": "キューインキ", "USen": "Ink Vac" },
    "innerId": 8,
    "remoteImgIdent": "Wsp_SpBlower00.webp",
  },
  "SpCastle": {
    "code": "SpCastle",
    "labels": {
      "KRko": "로열 크라켄",
      "JPja": "テイオウイカ",
      "USen": "Kraken Royale",
    },
    "innerId": 17,
    "remoteImgIdent": "Wsp_SpCastle00.webp",
  },
  "SpChariot": {
    "code": "SpChariot",
    "labels": {
      "KRko": "크랩 탱크",
      "JPja": "カニタンク",
      "USen": "Crab Tank",
    },
    "innerId": 12,
    "remoteImgIdent": "Wsp_SpChariot00.webp",
  },
  "SpChimney": {
    "code": "SpChimney",
    "labels": {
      "KRko": "스플래터컬러 스크린",
      "JPja": "スミナガシート",
      "USen": "Splattercolor Screen",
    },
    "innerId": 19,
    "remoteImgIdent": "Wsp_SpChimney00.webp",
  },
  "SpEnergyStand": {
    "code": "SpEnergyStand",
    "labels": {
      "KRko": "에너지 스탠드",
      "JPja": "エナジースタンド",
      "USen": "Tacticooler",
    },
    "innerId": 15,
    "remoteImgIdent": "Wsp_SpEnergyStand00.webp",
  },
  "SpFirework": {
    "code": "SpFirework",
    "labels": {
      "KRko": "디코이 캐넌",
      "JPja": "デコイチラシ",
      "USen": "Super Chump",
    },
    "innerId": 16,
    "remoteImgIdent": "Wsp_SpFirework00.webp",
  },
  "SpGreatBarrier": {
    "code": "SpGreatBarrier",
    "labels": {
      "KRko": "그레이트 배리어",
      "JPja": "グレートバリア",
      "USen": "Big Bubbler",
    },
    "innerId": 2,
    "remoteImgIdent": "Wsp_SpGreatBarrier00.webp",
  },
  "SpInkStorm": {
    "code": "SpInkStorm",
    "labels": { "KRko": "먹구름", "JPja": "アメフラシ", "USen": "Ink Storm" },
    "innerId": 5,
    "remoteImgIdent": "Wsp_SpInkStorm00.webp",
  },
  "SpJetpack": {
    "code": "SpJetpack",
    "labels": { "KRko": "제트 팩", "JPja": "ジェットパック", "USen": "Inkjet" },
    "innerId": 10,
    "remoteImgIdent": "Wsp_SpJetpack00.webp",
  },
  "SpMicroLaser": {
    "code": "SpMicroLaser",
    "labels": {
      "KRko": "메가폰 레이저 5.1ch",
      "JPja": "メガホンレーザー5.1ch",
      "USen": "Killer Wail 5.1",
    },
    "innerId": 9,
    "remoteImgIdent": "Wsp_SpMicroLaser00.webp",
  },
  "SpMultiMissile": {
    "code": "SpMultiMissile",
    "labels": {
      "KRko": "멀티 미사일",
      "JPja": "マルチミサイル",
      "USen": "Tenta Missiles",
    },
    "innerId": 4,
    "remoteImgIdent": "Wsp_SpMultiMissile00.webp",
  },
  "SpNiceBall": {
    "code": "SpNiceBall",
    "labels": {
      "KRko": "나이스옥",
      "JPja": "ナイスダマ",
      "USen": "Booyah Bomb",
    },
    "innerId": 6,
    "remoteImgIdent": "Wsp_SpNiceBall00.webp",
  },
  "SpPogo": {
    "code": "SpPogo",
    "labels": {
      "KRko": "울트라 착지",
      "JPja": "ウルトラチャクチ",
      "USen": "Triple Splashdown",
    },
    "innerId": 18,
    "remoteImgIdent": "Wsp_SpPogo00.webp",
  },
  "SpShockSonar": {
    "code": "SpShockSonar",
    "labels": {
      "KRko": "홉 소나",
      "JPja": "ホップソナー",
      "USen": "Wave Breaker",
    },
    "innerId": 7,
    "remoteImgIdent": "Wsp_SpShockSonar00.webp",
  },
  "SpSkewer": {
    "code": "SpSkewer",
    "labels": {
      "KRko": "샤크 라이드",
      "JPja": "サメライド",
      "USen": "Reefslider",
    },
    "innerId": 13,
    "remoteImgIdent": "Wsp_SpSkewer00.webp",
  },
  "SpSuperHook": {
    "code": "SpSuperHook",
    "labels": {
      "KRko": "쇼크 원더",
      "JPja": "ショクワンダー",
      "USen": "Zipcaster",
    },
    "innerId": 3,
    "remoteImgIdent": "Wsp_SpSuperHook00.webp",
  },
  "SpTripleTornado": {
    "code": "SpTripleTornado",
    "labels": {
      "KRko": "트리플 토네이도",
      "JPja": "トリプルトルネード",
      "USen": "Triple Inkstrike",
    },
    "innerId": 14,
    "remoteImgIdent": "Wsp_SpTripleTornado00.webp",
  },
  "SpUltraShot": {
    "code": "SpUltraShot",
    "labels": {
      "KRko": "울트라 샷",
      "JPja": "ウルトラショット",
      "USen": "Trizooka",
    },
    "innerId": 1,
    "remoteImgIdent": "Wsp_SpUltraShot00.webp",
  },
  "SpUltraStamp": {
    "code": "SpUltraStamp",
    "labels": {
      "KRko": "울트라 스탬프",
      "JPja": "ウルトラハンコ",
      "USen": "Ultra Stamp",
    },
    "innerId": 11,
    "remoteImgIdent": "Wsp_SpUltraStamp00.webp",
  },
} as const;
