// This file is auto-generated by scripts/generateWeaponConstants.ts

export const codes = [
  "SpBlower", // キューインキ
  "SpCastle", // テイオウイカ
  "SpChariot", // カニタンク
  "SpChimney", // スミナガシート
  "SpEnergyStand", // エナジースタンド
  "SpFirework", // デコイチラシ
  "SpGreatBarrier", // グレートバリア
  "SpInkStorm", // アメフラシ
  "SpJetpack", // ジェットパック
  "SpMicroLaser", // メガホンレーザー5.1ch
  "SpMultiMissile", // マルチミサイル
  "SpNiceBall", // ナイスダマ
  "SpPogo", // ウルトラチャクチ
  "SpShockSonar", // ホップソナー
  "SpSkewer", // サメライド
  "SpSuperHook", // ショクワンダー
  "SpTripleTornado", // トリプルトルネード
  "SpUltraShot", // ウルトラショット
  "SpUltraStamp", // ウルトラハンコ
] as const;

export const codeToData = {
  "SpBlower": {
    code: "SpBlower",
    label: "キューインキ",
    innerId: 8,
    remoteImgIdent: "Wsp_SpBlower00.png",
  },
  "SpCastle": {
    code: "SpCastle",
    label: "テイオウイカ",
    innerId: 17,
    remoteImgIdent: "Wsp_SpCastle00.png",
  },
  "SpChariot": {
    code: "SpChariot",
    label: "カニタンク",
    innerId: 12,
    remoteImgIdent: "Wsp_SpChariot00.png",
  },
  "SpChimney": {
    code: "SpChimney",
    label: "スミナガシート",
    innerId: 19,
    remoteImgIdent: "Wsp_SpChimney00.png",
  },
  "SpEnergyStand": {
    code: "SpEnergyStand",
    label: "エナジースタンド",
    innerId: 15,
    remoteImgIdent: "Wsp_SpEnergyStand00.png",
  },
  "SpFirework": {
    code: "SpFirework",
    label: "デコイチラシ",
    innerId: 16,
    remoteImgIdent: "Wsp_SpFirework00.png",
  },
  "SpGreatBarrier": {
    code: "SpGreatBarrier",
    label: "グレートバリア",
    innerId: 2,
    remoteImgIdent: "Wsp_SpGreatBarrier00.png",
  },
  "SpInkStorm": {
    code: "SpInkStorm",
    label: "アメフラシ",
    innerId: 5,
    remoteImgIdent: "Wsp_SpInkStorm00.png",
  },
  "SpJetpack": {
    code: "SpJetpack",
    label: "ジェットパック",
    innerId: 10,
    remoteImgIdent: "Wsp_SpJetpack00.png",
  },
  "SpMicroLaser": {
    code: "SpMicroLaser",
    label: "メガホンレーザー5.1ch",
    innerId: 9,
    remoteImgIdent: "Wsp_SpMicroLaser00.png",
  },
  "SpMultiMissile": {
    code: "SpMultiMissile",
    label: "マルチミサイル",
    innerId: 4,
    remoteImgIdent: "Wsp_SpMultiMissile00.png",
  },
  "SpNiceBall": {
    code: "SpNiceBall",
    label: "ナイスダマ",
    innerId: 6,
    remoteImgIdent: "Wsp_SpNiceBall00.png",
  },
  "SpPogo": {
    code: "SpPogo",
    label: "ウルトラチャクチ",
    innerId: 18,
    remoteImgIdent: "Wsp_SpPogo00.png",
  },
  "SpShockSonar": {
    code: "SpShockSonar",
    label: "ホップソナー",
    innerId: 7,
    remoteImgIdent: "Wsp_SpShockSonar00.png",
  },
  "SpSkewer": {
    code: "SpSkewer",
    label: "サメライド",
    innerId: 13,
    remoteImgIdent: "Wsp_SpSkewer00.png",
  },
  "SpSuperHook": {
    code: "SpSuperHook",
    label: "ショクワンダー",
    innerId: 3,
    remoteImgIdent: "Wsp_SpSuperHook00.png",
  },
  "SpTripleTornado": {
    code: "SpTripleTornado",
    label: "トリプルトルネード",
    innerId: 14,
    remoteImgIdent: "Wsp_SpTripleTornado00.png",
  },
  "SpUltraShot": {
    code: "SpUltraShot",
    label: "ウルトラショット",
    innerId: 1,
    remoteImgIdent: "Wsp_SpUltraShot00.png",
  },
  "SpUltraStamp": {
    code: "SpUltraStamp",
    label: "ウルトラハンコ",
    innerId: 11,
    remoteImgIdent: "Wsp_SpUltraStamp00.png",
  },
} as const;
