// This file is auto-generated by scripts/generateWeaponConstants.ts

export const codes = [
  "Beacon", // 점프 비컨
  "Bomb_Curling", // 컬링 밤
  "Bomb_Fizzy", // 탄산 밤
  "Bomb_Quick", // 퀵 밤
  "Bomb_Robot", // 로봇 밤
  "Bomb_Splash", // 스플래시 밤
  "Bomb_Suction", // 빨판 밤
  "Bomb_Torpedo", // 토피도
  "LineMarker", // 라인 마커
  "PointSensor", // 포인트 센서
  "PoisonMist", // 포이즌 미스트
  "Shield", // 스플래시 실드
  "Sprinkler", // 스프링클러
  "Trap", // 트랩
] as const;

export const codeToData = {
  "Beacon": {
    "code": "Beacon",
    "labels": {
      "KRko": "점프 비컨",
      "JPja": "ジャンプビーコン",
      "USen": "Squid Beakon",
    },
    "innerId": 8,
    "remoteImgIdent": "Wsb_Beacon00.png",
  },
  "Bomb_Curling": {
    "code": "Bomb_Curling",
    "labels": {
      "KRko": "컬링 밤",
      "JPja": "カーリングボム",
      "USen": "Curling Bomb",
    },
    "innerId": 6,
    "remoteImgIdent": "Wsb_Bomb_Curling00.png",
  },
  "Bomb_Fizzy": {
    "code": "Bomb_Fizzy",
    "labels": {
      "KRko": "탄산 밤",
      "JPja": "タンサンボム",
      "USen": "Fizzy Bomb",
    },
    "innerId": 5,
    "remoteImgIdent": "Wsb_Bomb_Fizzy00.png",
  },
  "Bomb_Quick": {
    "code": "Bomb_Quick",
    "labels": { "KRko": "퀵 밤", "JPja": "クイックボム", "USen": "Burst Bomb" },
    "innerId": 2,
    "remoteImgIdent": "Wsb_Bomb_Quick00.png",
  },
  "Bomb_Robot": {
    "code": "Bomb_Robot",
    "labels": { "KRko": "로봇 밤", "JPja": "ロボットボム", "USen": "Autobomb" },
    "innerId": 7,
    "remoteImgIdent": "Wsb_Bomb_Robot00.png",
  },
  "Bomb_Splash": {
    "code": "Bomb_Splash",
    "labels": {
      "KRko": "스플래시 밤",
      "JPja": "スプラッシュボム",
      "USen": "Splat Bomb",
    },
    "innerId": 0,
    "remoteImgIdent": "Wsb_Bomb_Splash00.png",
  },
  "Bomb_Suction": {
    "code": "Bomb_Suction",
    "labels": {
      "KRko": "빨판 밤",
      "JPja": "キューバンボム",
      "USen": "Suction Bomb",
    },
    "innerId": 1,
    "remoteImgIdent": "Wsb_Bomb_Suction00.png",
  },
  "Bomb_Torpedo": {
    "code": "Bomb_Torpedo",
    "labels": { "KRko": "토피도", "JPja": "トーピード", "USen": "Torpedo" },
    "innerId": 13,
    "remoteImgIdent": "Wsb_Bomb_Torpedo00.png",
  },
  "LineMarker": {
    "code": "LineMarker",
    "labels": {
      "KRko": "라인 마커",
      "JPja": "ラインマーカー",
      "USen": "Angle Shooter",
    },
    "innerId": 12,
    "remoteImgIdent": "Wsb_LineMarker00.png",
  },
  "PointSensor": {
    "code": "PointSensor",
    "labels": {
      "KRko": "포인트 센서",
      "JPja": "ポイントセンサー",
      "USen": "Point Sensor",
    },
    "innerId": 9,
    "remoteImgIdent": "Wsb_PointSensor00.png",
  },
  "PoisonMist": {
    "code": "PoisonMist",
    "labels": {
      "KRko": "포이즌 미스트",
      "JPja": "ポイズンミスト",
      "USen": "Toxic Mist",
    },
    "innerId": 11,
    "remoteImgIdent": "Wsb_PoisonMist00.png",
  },
  "Shield": {
    "code": "Shield",
    "labels": {
      "KRko": "스플래시 실드",
      "JPja": "スプラッシュシールド",
      "USen": "Splash Wall",
    },
    "innerId": 4,
    "remoteImgIdent": "Wsb_Shield00.png",
  },
  "Sprinkler": {
    "code": "Sprinkler",
    "labels": {
      "KRko": "스프링클러",
      "JPja": "スプリンクラー",
      "USen": "Sprinkler",
    },
    "innerId": 3,
    "remoteImgIdent": "Wsb_Sprinkler00.png",
  },
  "Trap": {
    "code": "Trap",
    "labels": { "KRko": "트랩", "JPja": "トラップ", "USen": "Ink Mine" },
    "innerId": 10,
    "remoteImgIdent": "Wsb_Trap00.png",
  },
} as const;
