// This file is auto-generated by scripts/generateWeaponConstants.ts

export const codes = [
  "Beacon", // ジャンプビーコン
  "Bomb_Curling", // カーリングボム
  "Bomb_Fizzy", // タンサンボム
  "Bomb_Quick", // クイックボム
  "Bomb_Robot", // ロボットボム
  "Bomb_Splash", // スプラッシュボム
  "Bomb_Suction", // キューバンボム
  "Bomb_Torpedo", // トーピード
  "LineMarker", // ラインマーカー
  "PointSensor", // ポイントセンサー
  "PoisonMist", // ポイズンミスト
  "Shield", // スプラッシュシールド
  "Sprinkler", // スプリンクラー
  "Trap", // トラップ
] as const;

export const codeToData = {
  "Beacon": {
    code: "Beacon",
    label: "ジャンプビーコン",
    innerId: 8,
    remoteImgIdent: "Wsb_Beacon00.png",
  },
  "Bomb_Curling": {
    code: "Bomb_Curling",
    label: "カーリングボム",
    innerId: 6,
    remoteImgIdent: "Wsb_Bomb_Curling00.png",
  },
  "Bomb_Fizzy": {
    code: "Bomb_Fizzy",
    label: "タンサンボム",
    innerId: 5,
    remoteImgIdent: "Wsb_Bomb_Fizzy00.png",
  },
  "Bomb_Quick": {
    code: "Bomb_Quick",
    label: "クイックボム",
    innerId: 2,
    remoteImgIdent: "Wsb_Bomb_Quick00.png",
  },
  "Bomb_Robot": {
    code: "Bomb_Robot",
    label: "ロボットボム",
    innerId: 7,
    remoteImgIdent: "Wsb_Bomb_Robot00.png",
  },
  "Bomb_Splash": {
    code: "Bomb_Splash",
    label: "スプラッシュボム",
    innerId: 0,
    remoteImgIdent: "Wsb_Bomb_Splash00.png",
  },
  "Bomb_Suction": {
    code: "Bomb_Suction",
    label: "キューバンボム",
    innerId: 1,
    remoteImgIdent: "Wsb_Bomb_Suction00.png",
  },
  "Bomb_Torpedo": {
    code: "Bomb_Torpedo",
    label: "トーピード",
    innerId: 13,
    remoteImgIdent: "Wsb_Bomb_Torpedo00.png",
  },
  "LineMarker": {
    code: "LineMarker",
    label: "ラインマーカー",
    innerId: 12,
    remoteImgIdent: "Wsb_LineMarker00.png",
  },
  "PointSensor": {
    code: "PointSensor",
    label: "ポイントセンサー",
    innerId: 9,
    remoteImgIdent: "Wsb_PointSensor00.png",
  },
  "PoisonMist": {
    code: "PoisonMist",
    label: "ポイズンミスト",
    innerId: 11,
    remoteImgIdent: "Wsb_PoisonMist00.png",
  },
  "Shield": {
    code: "Shield",
    label: "スプラッシュシールド",
    innerId: 4,
    remoteImgIdent: "Wsb_Shield00.png",
  },
  "Sprinkler": {
    code: "Sprinkler",
    label: "スプリンクラー",
    innerId: 3,
    remoteImgIdent: "Wsb_Sprinkler00.png",
  },
  "Trap": {
    code: "Trap",
    label: "トラップ",
    innerId: 10,
    remoteImgIdent: "Wsb_Trap00.png",
  },
} as const;
